### ISSUE TITLE
关于声卡的使用反馈和建议

### ISSUE THREAD

**Issue by gemini40** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#1]
老铁，您好，我的机器是dell i5 8300h hd1050 10.14.3 , 使用您的clover后感觉好多了，没有各种惊慌的问题然后突然重启。但是我在使用iphone自带的手机耳机插入电脑能用，音效很好，但是当我操作一些程序或者什么的时候，耳机会突然变成高频杂音，必须重启解决。

我曾用过github的一个近期的clover，我记得是可以手动切换耳机和内置扬声器的。应该是这个https://github.com/shenlinsl/DELL-XPS-15-9570-8950-4K-macOS-Mojave  ，这个clover驱动不错，但是会间歇性的突然黑屏重启，启动后出现“硬件恐慌”错误问题，很影响工作。不过这个clover可以切换内部和外部扬声器且无问题，我想如果可以话，是否能在您的clover基础上，把声卡驱动换成可以手动点击喇叭图标切换的驱动，万分感谢！换好后，可以将EFI发到我的邮箱吗？178555266@qq.com

**Comment by gemini40** [comment]
哦 ，我的屏幕是1080p的。我看配置文件里火狼的1080p是disable，不知道这个要不要打开。

**Comment by LuletterSoul** [comment]
@gemini40 您好，你提及的EFI我已测试过，确实会出现关于显卡的panic问题（我在远景论坛发表过此问题，无人提出解决方案），经测试只有Xigun和B兄的EFI工作最好。

关于显卡，你的理解正确，请将4K的disabled，开启1080P的，这个补丁可以解决睡眠问题。

关于您的声卡问题，按你的描述应该是layout注入不正确，请您提供对应ALC型号，我会尝试帮你解决。

**Comment by LuletterSoul** [comment]
@gemini40 另外，你可以自己尝试使用不同的layout-id（因为尝试不太的id是很麻烦的事）, 因为我的EFI是基于DSDT注入，需要学习相关的DSDT编译和反编译知识，https://github.com/RehabMan/Laptop-DSDT-Patch下有相关教程链接。

**Comment by gemini40** [comment]
@LuletterSoul 万分感谢！我的声卡应该是ALC298? 其实我也不太清楚。看到大家都说是298好像。我是xps15，9570，I5 8300H ,1080p,UHD630+1050(已经屏蔽)，然后我已经开启了1080p，并disable了4k。
就是这个声卡，如果能改成手动切换的就好了，应该就不会有间断性杂音。除此以外，这个clover可以取消-v模式么？啰嗦模式一直觉得怪怪的，总体而言这个clover除了声卡的切换，我想其他都工作非常好！

**Comment by M69W** [comment]
目前有大部分硬件驱动使用良好，
要是方便，不妨加个群
群里几乎有9570所有型号，也方便测试
Q群 929644389

目前群里也在整合你的clover, 力求完美！
