### ISSUE TITLE
请问下集显hd630能带的动4k屏幕吗？

### ISSUE THREAD

**Issue by axkza** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#103]
请问下集显hd630能带的动4k屏幕吗？我看好多都在说带不动4k屏幕，会卡的？就普通码码代码、浏览网页

**Comment by Mercury1993** [comment]
完全可以的。发自我的华为手机-------- 原始邮件 --------发件人： axkza <notifications@github.com>日期： 2020年9月8日周二 16:03收件人： LuletterSoul/Dell-XPS15-9570-macOS <Dell-XPS15-9570-macOS@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [LuletterSoul/Dell-XPS15-9570-macOS] 请问下集显hd630能带的动4k屏幕吗？ (#103)

请问下集显hd630能带的动4k屏幕吗？我看好多都在说带不动4k屏幕，会卡的？就普通码码代码、浏览网页
