### ISSUE TITLE
DW1830 Bluetooth unavailable from sleep in battery.

### ISSUE THREAD

**Issue by LuletterSoul** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#11]
ISSUE description:
* DW1830 BT is detected as BCM2045A0 when come out from sleep while in battery --> BT doesn't work properly: BT status turns into unavailable after a while.
* DW1830 BT is detected as BCM920703 when come out from sleep while on AC --> BT works with zero issue

问题描述：
* DW1830 蓝牙在使用电池状态下睡眠，唤醒后设备号被侦测BCM2045A0，工作不正常：一段时间后蓝牙状态变为不可用；
* DW1830 蓝牙在接通电源线时，唤醒后设备号被侦测为BCM920703，工作正常；

**Comment by LuletterSoul** [comment]
[See more discussions about this issue](https://www.tonymacx86.com/threads/dw1830-bluetooth-not-available-power-saving-issue.246350/page-5)

**Comment by bavariancake** [comment]
I commented on this issue you opened in my repo, take a look.

**Comment by LuletterSoul** [comment]
@bavariancake Thank you so much!  I found a hardware solution.It could be fixed by disabling `Pin 56` and `Pin 54` successfully.Check [jaymonkey’s post](https://www.tonymacx86.com/threads/bluetooth-randomly-not-available-after-sleep.266255/#post-1862126) to see more details.
