### ISSUE TITLE
1080p 开机时有白线一闪而过

### ISSUE THREAD

**Issue by luowencai** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#110]
请问要怎么处理，就是关掉了verbose的啰嗦模式后会出现 白线一闪 然后再出现白苹果界面进入系统

**Comment by M69W** [comment]
如果无法解决问题，
可以尝试用一下目前看到的更新时间最近的一个 EFI 
https://github.com/xxxzc/xps15-9570-macos
