### ISSUE TITLE
第一阶段与第二阶段苹果logo大小不一致

### ISSUE THREAD

**Issue by M69W** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#12]
logo大小不一致似乎跟 CustomLogo 和 NoEarlyProgress 这两个值有关：

比如说去掉 CustomLogo (和其自定义值Alternate) 并且 设置 NoEarlyProgress 为 false，这样 logo 便是一致了。

https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/blob/master/CLOVER/config.plist#L263 

https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/blob/master/CLOVER/config.plist#L273

**Comment by ZhenbPeng** [comment]
实测可以解决大小不一致的问题。

**Comment by LuletterSoul** [comment]
行之有效，下一个版本会整合！非常感谢。
