### ISSUE TITLE
 触摸手势与触摸屏无法使用

### ISSUE THREAD

**Issue by ZhenbPeng** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#13]
你好
首先非常感谢你分享的clover
之前一直在用Xigtun/xps-9570-mojave的配置，在升级14.4后发现触摸手势于触摸屏无法使用了。
在使用你的clover后可以正常使用HDMI输出与睡眠了（偶尔睡眠唤醒后，双屏状态内屏会画屏）！

我的机器是 
XPS15 9570
CPU i5-8300H
内存 8G
硬盘 东芝256SSD
显卡 1050 没有TI
屏幕 4K 触摸屏
BIOS 1.8.1
机器是海外代购的，低配4k版本

在了解VoodooI2C相关的资料后，在win设备管理器中发现我的HID设备共有两个，BIOS名称分别是_SB.PCI0.I2C1.TPD0与_SB.PCI0.I2C1.TPL1。
请问能否根据你的clover，来提供一些思路来驱动触摸设备。

**Comment by ZhenbPeng** [comment]
再继续测试了下，是我自己的问题，在吧触摸相关的kext放入sle后显示加载但是没效果，在放入clover后加上-v 参数可以正常使用触摸版与触摸屏了
请关闭此问题吧。

**Comment by LuletterSoul** [comment]
放入S/L/E 请重建缓存。

**Comment by napster93** [comment]
Hi
1st of all thank you very much for this. my XPS 15 is now running Mojave. Only problem is touchscreen is not working. 
Could you please help me out here, 
"Put in S/L/E and rebuild the cache." - And I dont clearely understand this. Could you please explain it bit more.
