### ISSUE TITLE
我的详情显示的是i7，但是我的cpu是i9 8950hk，这个问题怎么解决呢？

### ISSUE THREAD

**Issue by linkjane** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#14]
![image](https://user-images.githubusercontent.com/15264018/56708361-00805b00-674f-11e9-9685-628c555e2fb2.png)
那个smbios里面的型号是Macbook 15，1也是i9的那款，但是不知道为什么是i7，使用的config.plist是你提供的那个

**Comment by M69W** [comment]
[i9-9900K 处理器信息那如何正确显示i9 9900k 我这里显示3.6ghz 未知](http://bbs.pcbeta.com/viewthread-1811409-1-1.html)
