### ISSUE TITLE
声卡未驱动

### ISSUE THREAD

**Issue by w962402254** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#15]
我用了bavariancake的clover，但是声卡没有驱动，不知道什么原因
![image](https://user-images.githubusercontent.com/27877696/56793736-3a308f00-683f-11e9-9105-7d8c81964f63.png)
引导clover界面那个audio那个选项提示 'unknow HDA device vendor 8086,model a348'
可以帮我解答一下嘛，十分感谢

**Comment by LuletterSoul** [comment]
不明，这是不常见的问题。

**Comment by w962402254** [comment]
重启 选resetHRD 或者no caches瞎也能试出来，但是重启之后又驱动不了了，不知道原因是什么
