### ISSUE TITLE
Support for Intel i9-8950HK

### ISSUE THREAD

**Issue by dhruvdangi** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#16]
Can this be used for the i9 model of Dell XPS 9570, if not then what all changes will be required?

**Comment by mahoshojoHCG** [comment]
Yes, mine is XPS **9670** i9-8950HK model. It works well and no changes required.

**Comment by linkjane** [comment]
> Yes, mine is XPS **9670** i9-8950HK model. It works well and no changes required.

Do yours can detect fans? mine can't detect fans and very nosie，and sometime the screen very slow，I don't know why!
![image](https://user-images.githubusercontent.com/15264018/57462085-c6fd3300-72aa-11e9-8658-473574b530a8.png)
![image](https://user-images.githubusercontent.com/15264018/57462108-d7151280-72aa-11e9-81b4-bacf9a168b1c.png)

**Comment by mahoshojoHCG** [comment]
> > Yes, mine is XPS **9670** i9-8950HK model. It works well and no changes required.
> 
> Do yours can detect fans? mine can't detect fans and very nosie，and sometime the screen very slow，I don't know why!
> ![image](https://user-images.githubusercontent.com/15264018/57462085-c6fd3300-72aa-11e9-8658-473574b530a8.png)
> ![image](https://user-images.githubusercontent.com/15264018/57462108-d7151280-72aa-11e9-81b4-bacf9a168b1c.png)

我也是检测不到风扇，但是我的风扇并没有那么吵，温度也差不多。按照描述你应该显卡应该没驱动上，装好后有没有运行`sudo kextcache -i `然后换配置文件为`config.plist`？

**Comment by linkjane** [comment]
> > > Yes, mine is XPS **9670** i9-8950HK model. It works well and no changes required.
> > 
> > 
> > Do yours can detect fans? mine can't detect fans and very nosie，and sometime the screen very slow，I don't know why!
> > ![image](https://user-images.githubusercontent.com/15264018/57462085-c6fd3300-72aa-11e9-8658-473574b530a8.png)
> > ![image](https://user-images.githubusercontent.com/15264018/57462108-d7151280-72aa-11e9-81b4-bacf9a168b1c.png)
> 
> 我也是检测不到风扇，但是我的风扇并没有那么吵，温度也差不多。按照描述你应该显卡应该没驱动上，装好后有没有运行`sudo kextcache -i `然后换配置文件为`config.plist`？

突然变成中文了。。。显卡没驱动上吗？但是显存已经是2048MB了，安装用install config那个之后直接换的config.plist
![image](https://user-images.githubusercontent.com/15264018/57499033-be3f4800-7310-11e9-9654-1281c58f9c44.png)

**Comment by mahoshojoHCG** [comment]
> > > > Yes, mine is XPS **9670** i9-8950HK model. It works well and no changes required.
> > > 
> > > 
> > > Do yours can detect fans? mine can't detect fans and very nosie，and sometime the screen very slow，I don't know why!
> > > ![image](https://user-images.githubusercontent.com/15264018/57462085-c6fd3300-72aa-11e9-8658-473574b530a8.png)
> > > ![image](https://user-images.githubusercontent.com/15264018/57462108-d7151280-72aa-11e9-81b4-bacf9a168b1c.png)
> > 
> > 
> > 我也是检测不到风扇，但是我的风扇并没有那么吵，温度也差不多。按照描述你应该显卡应该没驱动上，装好后有没有运行`sudo kextcache -i `然后换配置文件为`config.plist`？
> 
> 突然变成中文了。。。显卡没驱动上吗？但是显存已经是2048MB了，安装用install config那个之后直接换的config.plist
> ![image](https://user-images.githubusercontent.com/15264018/57499033-be3f4800-7310-11e9-9654-1281c58f9c44.png)

那你就是没运行sudo kextcache -i ， 你再读一下说明
