### ISSUE TITLE
请问丐版的9570安装

### ISSUE THREAD

**Issue by ATFieldBeast** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#19]
首先谢谢dalao的付出
然后我是丐版的9570，8300h不带独显的，也可以直接套用这套clover吗？

**Comment by LuletterSoul** [comment]
自行测试。

**Comment by ATFieldBeast** [comment]
> 自行测试。

装上了，不过出现了
1）相同的[声卡情况](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/1#issue-426255568)（我发现是在CPU高负载（比如开网页直播时）的时候就会变成尖锐的高频音）；

<s>2）相同的风扇cpu温度很低的时候也猛转，[kernel_task占用超100%](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2#issuecomment-483485407)的情况；</s>

3）相同的电池睡眠后唤醒[蓝牙丢失](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/11#issue-435502666)的情况；

4）雷电3无法使用（无法读取Mantiz盒子里的外置硬盘、有线网口和usbhub（独显我只有n卡，本来也不能驱动，就不知道a卡能不能驱动了），但是雷电3口的供电正常，能够充电）；

其中2）通过您的[注入layout id 72](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2#issuecomment-482779467)得到了解决，kernel_task占用正常了，温度和风扇也在一个能接受的正常平衡了；

不过在进行2）的修复后，1）的声卡问题直接变成了外扬声器正常，插入耳机没有音频也一直有高频声，开始有音频输出后则是声音一顿一顿的；

bios是最近更新的1.10.1。

**Comment by ATFieldBeast** [comment]
这是我在macos下用getdump得到的信息


Probing codec #0...
 HDA Codec #0: Realtek (Unknown)
 HDA Codec ID: 0x10ec0298
       Vendor: 0x10ec
       Device: 0x0298
     Revision: 0x01
     Stepping: 0x03
PCI Subvendor: 0x087c1028
	startNode=1 endNode=2
	Found audio FG nid=1 startNode=2 endNode=38 total=36


+-------------------------------+
| DUMPING Playback/Record Paths |
+-------------------------------+

Playback:

    nid=23 [pin: Speaker (Analog)]
      |
      + <- nid=12 [audio mixer] [src: mix] bindSeq=00000001

             |
             + <- nid=2 [audio output] [src: pcm] bindSeq=00000001


Record:

    nid=9 [audio input]
      |
      + <- nid=34 [audio selector] [src: speaker, monitor] bindSeq=00000001

             |
             + <- nid=29 [beep widget]
             + <- nid=18 [pin: Microphone (Digital)] [src: monitor] bindSeq=00000001


Input Mix:

    nid=12 [audio mixer]
      |
      + <- nid=2 [audio output] [src: pcm] bindSeq=00000001


    nid=13 [audio mixer]
      |
      + <- nid=3 [audio output] [src: pcm] bindSeq=00000001




+-------------------------------+
| DUMPING Playback/Record Paths |
+-------------------------------+

Playback:

    nid=33 [pin: Headphones (Black Left)]
      |
      + <- nid=13 [audio mixer] [src: mix] bindSeq=00000001

             |
             + <- nid=3 [audio output] [src: pcm] bindSeq=00000001

**Comment by ATFieldBeast** [comment]
<s>好了，现在好像正常了，之前是直接把你发的那个SSDT-Config.zip放了进去，结果声卡就炸了。后面我是在clover里自己手动注入72就好了

不过目前发现了新问题，就是我开了dellbios里的链接电源开机（因为我都是盒盖外接的），然后这样子
1）合着盖子，耳机孔不插耳机开机的话，hdmi就会没有音频输出，得把盖子打开再关上（或者拔插hdmi）一次才能让音频走hdmi，此时耳机孔再插入耳机也没有声音（扬声器状态一直是扬声器）；

2）合着盖子，耳机孔插耳机开机的话，hdmi还是会没有音频输出，得把盖子打开再关上（或者拔插hdmi）一次才能让音频走hdmi，不过此时耳机孔再插入耳机会有声音（扬声器状态变成耳机，拔插正常切换）

以上两种情况扬声器都正常。

alcfix安装了，仍没有解决这个bug</s>

注入72后还是发现会突然变成刺耳的高频音，但是占用正常了

**Comment by ChanaLii** [comment]
@ATFieldBeast 跟你同样的xps 9570配置，我更换了30多个EFI尝试安装一直安装不上，进入clover界面后选择“Boot macOS Install from Install macOS Mojave”向磁盘写入macOS系统，进度条大约在2/3的位置自动重启；重启后出现“新的启动项”，手动选择“新的启动项”进入“苹果图标界面”，进度条显示“剩余大约2分钟”忽然弹出日志错误页面“未能完成macOS安装”。我使用 LuletterSoul 的EFI也是如此。请问你在安装时做了哪些配置？Bios需要升级到最新版吗？

	
以下是我的笔记本配置：
（在原配置上新增了一块SATA固态硬盘）
电脑型号	戴尔 XPS 15 9570 笔记本电脑  (扫描时间：2019年05月15日)
操作系统	Windows 10 64位 ( DirectX 12 )
	
处理器	英特尔 Core i5-8300H @ 2.30GHz 四核
主板	戴尔 082GV9 ( C240 Series 芯片组 Family - A30E )
内存	8 GB ( 镁光 DDR4 2666MHz )
主硬盘	**三星 SSD 860 EVO 500GB ( 500 GB / 固态硬盘 )** /  **东芝 NVMe TOSHIBA 256GB**
显卡	英特尔 UHD Graphics 630 ( 128 MB / 戴尔 )
显示器	夏普 SHP149A ( 15.5 英寸  )
声卡	瑞昱  @ 英特尔 High Definition Audio 控制器
网卡	Atheros Killer Wireless-n/a/ac 1535 Wireless Network Adapter / Bigfoot Networks

**Comment by ATFieldBeast** [comment]
> @ATFieldBeast 跟你同样的xps 9570配置，我更换了30多个EFI尝试安装一直安装不上，进入clover界面后选择“Boot macOS Install from Install macOS Mojave”向磁盘写入macOS系统，进度条大约在2/3的位置自动重启；重启后出现“新的启动项”，手动选择“新的启动项”进入“苹果图标界面”，进度条显示“剩余大约2分钟”忽然弹出日志错误页面“未能完成macOS安装”。我使用 LuletterSoul 的EFI也是如此。请问你在安装时做了哪些配置？Bios需要升级到最新版吗？
> 
> 以下是我的笔记本配置：
> （在原配置上新增了一块SATA固态硬盘）
> 电脑型号	戴尔 XPS 15 9570 笔记本电脑 (扫描时间：2019年05月15日)
> 操作系统	Windows 10 64位 ( DirectX 12 )
> 
> 处理器	英特尔 Core i5-8300H @ 2.30GHz 四核
> 主板	戴尔 082GV9 ( C240 Series 芯片组 Family - A30E )
> 内存	8 GB ( 镁光 DDR4 2666MHz )
> 主硬盘	**三星 SSD 860 EVO 500GB ( 500 GB / 固态硬盘 )** / **东芝 NVMe TOSHIBA 256GB**
> 显卡	英特尔 UHD Graphics 630 ( 128 MB / 戴尔 )
> 显示器	夏普 SHP149A ( 15.5 英寸 )
> 声卡	瑞昱 @ 英特尔 High Definition Audio 控制器
> 网卡	Atheros Killer Wireless-n/a/ac 1535 Wireless Network Adapter / Bigfoot Networks

我是先就去除了去除 -v 模式，把VoodooI2C.kext,VoodooI2CHID.kext,VoodooPS2Controller.kext都删掉了，然后进系统后再安装到S/L/E（不过这样在装触摸板驱动前触摸板和键盘都用不了，得外接键盘和鼠标进行安装与设置
