### ISSUE TITLE
关于cpu频率和触摸板问题

### ISSUE THREAD

**Issue by chenjh-8** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#2]
[你好，首先先感谢你，使用你的EFI后电脑感觉完善很多。但依然还存在比较影响使用的问题。第一cpu频率一直处于高频运转状态，即使我在普通浏览网页，风扇声音也较大；第二，触摸板无法对某个窗口进行快速双击按住并拖动（我不确定mac是否支持这样操作，至少window下是可以的）！最后再次感谢你！并附上几张图！
![18D23685858D8C8CDB0002B8FBC65286](https://user-images.githubusercontent.com/38275824/55408192-148ecd80-5592-11e9-8b4f-fc79faf6a454.jpg)
<img width="800" alt="QQ20190402-213413@2x" src="https://user-images.githubusercontent.com/38275824/55408263-3c7e3100-5592-11e9-958b-4143cfdcaf1a.png">
![FDA176E246A54F08E0979F9F8D9A205F](https://user-images.githubusercontent.com/38275824/55408293-4dc73d80-5592-11e9-94ee-187f82a37c37.jpg)

**Comment by ghost** [comment]
双击拖动在MacBookPro13 2018上，经过测试发现确实无法拖动，是Mac系统的问题。

**Comment by LuletterSoul** [comment]
@chenjh-8 
1. 提供机型和配置
2. 检查一下活动监视器中的CPU项，有无异常程序
3. 替代方案：辅助功能->鼠标和触控板->开启三指拖动，实现拖拽效果

**Comment by chenjh-8** [comment]
> @chenjh-8
> 
> 1. 提供机型和配置
> 2. 检查一下活动监视器中的CPU项，有无异常程序
> 3. 替代方案：辅助功能->鼠标和触控板->开启三指拖动，实现拖拽效果

**Comment by chenjh-8** [comment]
@LuletterSoul  
1.机型配置与你一模一样
2.cpu 活动项有个叫kernel_task 进程 经常占用百分百
3.手势在你回复前我已经百度找到此方案

**Comment by LuletterSoul** [comment]
@chenjh-8 尝试注入layout id 72.据一些人反馈，错误的声卡id可能会导致kernel task繁忙

[SSDT-Config.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3075808/SSDT-Config.zip)

**Comment by chenjh-8** [comment]
@LuletterSoul 我注入后依然没有任何改观。电脑开机后正常运行,kernel_task占用cpu百分之二十多。当我打开idea、chrome 后，风扇开始转动起来了，而且转速不稳定时快时慢，kernel_task保持百分百多一点。即使我将idea，chrome关闭，kernel_task依然不变，电池两个小时就被消耗完。我查阅了很多资料，白苹果也有这样问题，其中有人说更换温度传感器后解决！还有一个我忘记说了，我没有更换网卡，使用USB网卡，是否受相关驱动所影响，但是我吧驱动卸载了问题依然存在。暂且先放弃了，再次感谢你！

**Comment by tofuliang** [comment]
@chenjh-8 你说的快速双击按住并拖动,Mac是不支持的,但是有另外的[操作方法](https://sspai.com/post/44173)

**Comment by josangmi** [comment]
双击拖动的功能 ，我在surface pro4 安装的Mac里面使用很好，但是在9570当中就不行了，让我很困惑。不知道哪里出问题了。 是不是要手动写文件开启呢。

**Comment by WuLongMiTaoLaiYiDa** [comment]
> @chenjh-8 尝试注入layout id 72.据一些人反馈，错误的声卡id可能会导致kernel task繁忙
> 
> [SSDT-Config.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3075808/SSDT-Config.zip)

声卡已经用id注入72，耳机不响。算了，鱼和熊掌不可兼得，注入30用电池睡眠之后就电流声，kernel task 占用140%。
另外最近根据QQ群友的方法，删除了触摸板的I2C相关的两个驱动，只留下了VoodooPS2Controller.kext驱动，kernel task cpu占用由原先的30%左右下降至7%到9%之间
目前三指手势和四指手势不能用了，还是鱼和熊掌不能兼得
不论怎样，感谢楼主一直以来在更新这个帖子，给了大家更多的思路，让更多的9570用户用上黑苹果，谢谢啦！

**Comment by w962402254** [comment]
> > @chenjh-8 尝试注入layout id 72.据一些人反馈，错误的声卡id可能会导致kernel task繁忙
> > [SSDT-Config.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3075808/SSDT-Config.zip)
> 
> 声卡已经用id注入72，耳机不响。算了，鱼和熊掌不可兼得，注入30用电池睡眠之后就电流声，kernel task 占用140%。
> 另外最近根据QQ群友的方法，删除了触摸板的I2C相关的两个驱动，只留下了VoodooPS2Controller.kext驱动，kernel task cpu占用由原先的30%左右下降至7%到9%之间
> 目前三指手势和四指手势不能用了，还是鱼和熊掌不能兼得
> 不论怎样，感谢楼主一直以来在更新这个帖子，给了大家更多的思路，让更多的9570用户用上黑苹果，谢谢啦！

老哥，我之前也遇到这个问题，我试了一下好像注入29可以解决这个问题，你可以试一下，耳机可以响，并且睡眠了开机后kernel_task也不会变高
