### ISSUE TITLE
English translation readme

### ISSUE THREAD

**Issue by toonvanstrijp** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#20]
Is there someone that could please provide and english version of the readme file?

I'm looking to different kind of configurations and would like to choose the best working one for my laptop.

Right now I'm using: [https://github.com/bavariancake/XPS9570-macOS](https://github.com/bavariancake/XPS9570-macOS).

Is this configuration giving more functionalities/battery performance?

**Comment by LuletterSoul** [comment]
@ToonvanStrijp The configuration of bavariancake is good enough actually,expect touch pad.
You can only use related voodooI2C kexts in my repository.
My English isn't native,so I have to show my apologizes for not providing english version of the readme file in time.

**Comment by toonvanstrijp** [comment]
@LuletterSoul Alright! And don't be sorry! It's okaay ;). One other thing. How can I debug/improve the battery life? Since the battery life is pretty bad.... Right now I'm using the Intel Power Gadget but I don't think this is showing the total power usage?
