### ISSUE TITLE
关于触摸板双击拖动

### ISSUE THREAD

**Issue by josangmi** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#22]
双击触摸同样的设置我在surface pro4的mac上面是可以使用的。
  但是9570上面就不能用了，不知道是不是要手动加入文件，但是网上的好像都不是10.14的，根本找不到对应文件。 三指还是不太好用，有成功的吗？谢谢。

**Comment by LuletterSoul** [comment]
当触控板被识别成鼠标时，双击拖拽才可以被被触控板激活。

另外，请提供有普众测试性意义的ISSUE，细枝末节的BUG不在仓库考虑范围。
