### ISSUE TITLE
Dell DA300 网卡和外接键盘

### ISSUE THREAD

**Issue by josangmi** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#23]
Dell Da300接上去，驱动都等认出来，但是只有HDMI可以用，有线网卡显示已连接但实际不能用，不知道何故。 键盘在clover选系统界面很正常，但是进到mac就失灵了，无法识别。但是在系统识别里面可以看到。

**Comment by LuletterSoul** [comment]
我没有设备，故无法测试。如果扩展坞有驱动，建议先在windows下装好驱动。。

**Comment by josangmi** [comment]
键盘应该是驱动问题，暂时换了普通键盘一切正常。 网卡就比较神奇了，开DHCP获取不到地址永远是169的默认地址，手动指定地址也没用，感觉只是网线连接了，也显示USB LAN正常，但是不工作。不知道可以在哪做设置。

**Comment by josangmi** [comment]
DA300 的有线网卡可以正常使用了，但是必须要一直打开终端执行下面的命令，
sudo tcpdump -i en2 src host 192.168.1.1
不知道为什么。也不知道原理。哪位老铁对这个熟悉的，帮忙琢磨一下，谢谢。

**Comment by LuletterSoul** [comment]
请确保网口内建，端口为en0

**Comment by josangmi** [comment]
我的是 en2。 好奇怪不知道是不是因为usb的关系，昨天观察了一下发现要将网卡设成混杂模式就可以了。但是ifconfig 的命令macox不支持，到现在还没找到办法，我尝试下看怎么改成en0，谢谢。

**Comment by josangmi** [comment]
bios关掉wifi将网卡设成en0了，但是问题依旧，混杂模式还不好设置，一头包。

**Comment by wtdcode** [comment]
我的da300也一样（

**Comment by ATFieldBeast** [comment]
我的wd15也是，得一直挂着tcpdump才能分配到地址，已是en0

**Comment by josangmi** [comment]
可能是macos不支持USB 网卡？ 不知道升级到10.14.5 能解决不。

**Comment by wtdcode** [comment]
@josangmi 我的AX88179 有线网卡没什么问题，我觉得这个问题很大可能还是 TypeC 口自己问题上。

**Comment by LuletterSoul** [comment]
据我的理解是，你需要使用这条Linux命令强制OS监听en2网口，截获主机192.168.1.1发送的所有数据。也就是说，你通过DA300连接的网卡是有数据的，只是OS没有收到网络数据包。我没有猜错的话，OS默认监听的网端应该是en0，我不知道是不是DA300改变了网络的路由方式导致了这个结果。

我可以给你提供一个折中方案：建立一个开机自动运行的超级权限的sh，在后台运行，这样你的终端就不用一直打开了。希望你能早日找到完美解决。

**Comment by M69W** [comment]
目前用的也是DA300,
需要驱动
OS X driver for Intel onboard LAN
1. https://github.com/RehabMan/OS-X-Intel-Network/blob/master/README.md 这个网址中的
https://bitbucket.org/RehabMan/os-x-intel-network/downloads/ 下载驱动 clover对应目录下

2.这个是新的，不过没有测试
https://github.com/acidanthera/IntelMausi/releases

目前使用1.中的驱动，有线网线接DA300正常使用。

**Comment by josangmi** [comment]
USB 10/100/1000 LAN：

  类型：	USB
  BSD 名称：	en0
  Kext 名称：	AppleUSBECM.kext
  位置：	/System/Library/Extensions/AppleUSBECM.kext
  版本：	5.0.0
不知道哪里没弄好了。驱动复制到clover了。启动之后还是不行。

**Comment by ATFieldBeast** [comment]
@josangmi @wtdcode @LuletterSoul 
我搞定了，原来是macos好像本来就没有这块网卡（Realtek 8153）的驱动，自己打一个就行了，Realtek官方也有提供
https://gist.github.com/MadLittleMods/3005bb13f7e7178e1eaa9f054cc547b0
装好之后重启就可以用了，然后系统信息里以太网卡里就没有它的信息了，而是到了usb一栏下，似乎这样才是正常的
[Ethernet_driver-RTUNICv1.0.17.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3305323/Ethernet_driver-RTUNICv1.0.17.zip)

**Comment by wtdcode** [comment]
@ATFieldBeast 
Good job！
其实我感觉也是没有驱动，因为我的AX88179也是类似症状打了驱动就好了，然后一直没用那个网口就忘了。

**Comment by josangmi** [comment]
@ATFieldBeast 太优秀了，我回去了赶紧试试，不过有一个疑虑，其实我现在的网卡就是显示在USB下面。所以非常的奇怪。感觉驱动装好了。

**Comment by josangmi** [comment]
验证可用，非常感谢各位，可以关闭了。

**Comment by M69W** [comment]
~~DA300 不支持热插拨，开机状态下，无法获取USB 有线网络~~

可以了，目前使用https://github.com/xxxzc/xps15-9570-macos，正常使用
