### ISSUE TITLE
Support of DW1560 

### ISSUE THREAD

**Issue by dhruvdangi** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#26]
On replacing the stock wifi card with DW1560 with BCM94352ZAE_3.
Is it because of the BCM is BCM94352ZAE_3 and not BCM94352Z?
I ordered it from Dell
Network preferences shows Wifi option but nothing happens on clicking Turn Wifi On
System Information shows:
Ethernet Cards: This computer does not appear to have any PCI Ethernet cards installed.
Network> Wifi: 
`Software Versions:
  CoreWLAN:	13.0 (1370.8)
  CoreWLANKit:	13.0 (1370.8)
  Menu Extra:	13.0 (1376.3)
  System Information:	12.0 (1300.2)
  IO80211 Family:	12.0 (1200.12.2)
  Diagnostics:	1.0 (805)
  AirPort Utility:	6.3.9 (639.9)
  Interfaces:
en0:
  Card Type:	AirPort Extreme  (0x14E4, 0x19)
  Firmware Version:	Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
  MAC Address: correct-mac-address
  Locale:	Unknown
  Country Code:	#a
  Supported PHY Modes:	802.11 a/b/g/n/ac
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  AirDrop:	Supported
  AirDrop Channel:	0
  Auto Unlock:	Supported
  Status:	Off`

**Comment by LuletterSoul** [comment]
DW1560 and DW1830 should be supported in this EFI.

**Comment by dhruvdangi** [comment]
Finally got it working, 
Had to tape out pins 54, 56.
This issue can be closed now

**Comment by dhruvdangi** [comment]
Finally got it to work, had to tape out pin 54, 56.

**Comment by eamigo86** [comment]
Hello, @dhruvdangi, I followed your advice and I covered the pins 54 and 56 with tape. (Follow this [guide](https://lybomudr.ru/ru/131-zapuskaem-wi-fi-modul-pci-express-m-2-ngff-bcm94352z-bcm94352zae-dw1560-pod-windows-10-v-acer-v3-371-i-drugikh.html)). But now the wifi works fine and the Bluetooth does not even appear in the System settings. Any suggestions for that?

**Comment by eamigo86** [comment]
Well, I finally get working Bluetooth after upgrade the BIOS. Thanks
