### ISSUE TITLE
Post-Installation steps

### ISSUE THREAD

**Issue by andresandiah** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#27]
Hi LuletterSoul, First of all: THANK YOU! This finally let me the chance to install Mac OS on my XPS 9570

I don't know Chinese at all and it's a little hard for me to know what I have to do after the installation has finished.

Already ran the command line you suggested and changed to the config.plist too. Is there more to do? Please help me out.

Do I have to install a kext?

**Comment by LuletterSoul** [comment]
There are two config files for different goals.`config_install.plist` is used to install OS only.
`config.plist` is the really thing to drive our machine.
Basic steps like as follwoing:
1. After installing Mac OS ,you should using config_install.plist to enter system .
2. Use `Kext Utility` or run `sudo kextcache -i /` ,rebuild kext cache.
3. Restart
4. If your machine is belong to 4K version, you could use the `config.plist` to drive 4K plane and enjoy it directly. or you have to  edit the .plist and enable  DHCP  patch for 1080P not 4K  in `Kernel and Kext Patches` item.

**Comment by andresandiah** [comment]
I got everything ok until step 3. Dont really know how to perform step 4 and what to search for in the config.plist

Also, seems like the thunderbolt port cant recognize usb c drives connected to it. Is that a common problem?

**Comment by erenatas** [comment]
@LuletterSoul do we really need to do kextcache -i since that the kexts are on EFI? Isn't kextcache installing kexts in S/L/E?

**Comment by sidbmw** [comment]
> I got everything ok until step 3. Dont really know how to perform step 4 and what to search for in the config.plist

+1

What do I have to do for it to work on my 1080p laptop?

**Comment by morristai** [comment]
@andresandiah    @sidbmw    You can use clover configurator to tweak `.plist`, the` Kernel and Kext Patches ` will show up on the left side, notice that there's some typo under Comment, but the code is fine. I've successfully booted up with this tweak with 1080p display.
![螢幕快照 2019-06-18 上午12 49 03](https://user-images.githubusercontent.com/10728152/59622092-3fd19380-9163-11e9-8cc1-e9e8f7ca95df.png)

**Comment by andresandiah** [comment]
in clover configurator i did setup the KextsToPatch just as you did, but im gettin kernel panics at gIOlockscreenState. The stock "4k" plist was working fine (i have a 1080p xps)

**Comment by morristai** [comment]
@andresandiah  I have random kernel panics on boot up even when using "4k" .plist. I found it really hard to find which part of kexts caused this issue. Maybe @LuletterSoul  can give us some answer.（ 其實我非常想為這個專案貢獻，尤其現在我是用這個hackintosh repo作為主要的工作筆記本，如果有什麼需要我的地方都可以儘管提出來，我非常樂意去研究。）

**Comment by wormz30** [comment]
Hey @LuletterSoul after a few days of going through the process, i finally got Mojave installed and running... however, despite running kextcache, and restarting, I cannot run Mojave without the USB stick. When i try to run off of the SSD, the laptop says, "No bootable devices found." Any help?

**Comment by sidbmw** [comment]
Make sure to Mount EFI before installing onto SSD (You could use Clover Confugurator for this).

I followed this https://www.reddit.com/r/Dell/comments/c2qciq/dell_xps_9570_mojave_guide/

Also here's my issue that has some valuable info that you may want... https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/31

**Comment by wormz30** [comment]
> Make sure to Mount EFI before installing onto SSD (You could use Clover Confugurator for this).
> 
> I followed this https://www.reddit.com/r/Dell/comments/c2qciq/dell_xps_9570_mojave_guide/
> 
> Also here's my issue that has some valuable info that you may want... #31

Perfecto! I got in and everything started working, but after a few restarts, now it reboots everytime it hits the apple logo. I did notice however, i'm getting the 4k "small" apple logo. and then it reboots. Any advice there?

**Comment by sidbmw** [comment]
It crashes for me as well and I believe everyone else....Kernel Panic.

It should go boot after crashing a couple times though. Not sure how to fix that.

**Comment by wormz30** [comment]
Interesting. I went and ran kextcache

**Comment by sidbmw** [comment]
Gotta run kextcache every time you change something apparently.

**Comment by wormz30** [comment]
Yeah that definitely fixed the problem. The next thing I’m running into is insanely slow wifi on my 1830 card. Anyone else run into this problem?

**Comment by wormz30** [comment]
Anyone else running into problems where sleep is a problem or where the laptop restarts after closing and opening the laptop screen?

**Comment by LuletterSoul** [comment]
The `Kernel and Kext Patched` for fixing 4k output is duplicated in the current release version, please focus on `Devices/Properties` item .When you open the `config.plst` with `Clover Configurator`，you will see the item as below:

<img width="1325" alt="Screen Shot 2019-07-06 at 6 25 39 PM" src="https://user-images.githubusercontent.com/21377419/60754988-e4851980-a01b-11e9-97e7-15186ce8b5b7.png">

When `dpcd-max-link-rate` = `<14000000>` ，the config will drive the 4k display.
When `dpcd-max-link-rate` = `<0A000000>`， the config will drive the 1080p display.

For the convenience, I make two `config.plist` for two options.The default `config.plist` is for 4K and the other `config_1080p.plist` is for 1080p.

All you need is to use `config_install.plist` to complete Mojave installation.You can learn more details for ReadME if you understand Chinese.

`

**Comment by LuletterSoul** [comment]
@diaper151 What's do you mean about the `random panics` ?

**Comment by sidbmw** [comment]
@LuletterSoul I get random panics as well.

When booting up/rebooting it crashes right before the apple logo and reboots and says "System was rebooted due to Panic". This happens multiple times during boot sometimes. Sometimes it works normally.

**Comment by LuletterSoul** [comment]
@sidbmw 
Did you remove `-v` boot arg from config.list ? 
You have to install `VoodooI2C.kext`,  `VoodooI2CHID.kext`,  `VoodooPS2Controller.kext` from `Clover/kexts/other` into `L/E` or `S/L/E` if you remove `-v`.

**Comment by sidbmw** [comment]
I didn't change anything. I downloaded the latest git commit and copy
pasted.

**Comment by LuletterSoul** [comment]
@sidbmw Please try to install ` VoodooI2C.kext`,` VoodooI2CHID.kext`, `VoodooPS2Controller.kext`  into `L/E` or `S/L/E` using `Kext Utility`
