### ISSUE TITLE
Support for Catalina 10.15

### ISSUE THREAD

**Issue by bullerwins** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#29]
What would be needed to boot Catalina 10.15 Beta 1?

**Comment by erenatas** [comment]
Have you tried it first?

**Comment by sidbmw** [comment]
Someone try it..I would if I didn't have exams and coding challenges :(

**Comment by sidbmw** [comment]
Doesn't work...

**Comment by LuletterSoul** [comment]
Catalina should be supported only you use the newest WEG, Luli, AppleALC and so on.But I don't recommend Catalina 10.15 because It's on public beta stage.Mojave 10.14.5 is stable enough,I won't task risks of updating to Cataline if I were you.

**Comment by LuletterSoul** [comment]
This repo fully supports for Catalina.Close it as fixed.
