### ISSUE TITLE
Da300 typec不能hdmi输出 Xigtun的可以  

### ISSUE THREAD

**Issue by QQ402164452** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#3]
Da300 typec不能hdmi输出 Xigtun的可以  改了什么地方吗

**Comment by M69W** [comment]
只需要改下
Board-ID
https://github.com/Xigtun/xps-9570-mojave/blob/master/EFI/CLOVER/config.plist#L534
https://github.com/Xigtun/xps-9570-mojave/blob/master/EFI/CLOVER/config.plist#L535
不过看了下，这个是一样的

要是还是不行，不妨看下这里说的
https://github.com/M69W/XPS-15-9570-macOS-Mojave/issues/2

**Comment by LuletterSoul** [comment]
@M69W 现在的配置是依赖于iMac14的board-id驱动typec转接，有时间会测试其他方案。
