### ISSUE TITLE
MacBook Supplemental Update

### ISSUE THREAD

**Issue by andresandiah** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#30]
Hi, did anyone else got a "Supplemental Update for Macbook Pro" in the software update settings? 
If so, did you manage to install it successfully? Or should I avoid it at all cost.

**Comment by sidbmw** [comment]
Did you end up trying?

**Comment by chinmayjade** [comment]
I got it ignored it. Thought it would break it.

**Comment by andresandiah** [comment]
I tried several times and ended up with a broken install.
I got it working at the end. Plug your macOS mojave installer USB (the one that you used to install the hackintosh): after that start the update process: wait for the first reboot, press F12 and boot from the USB: select "config_install.plist" and run it.

note: make sure that you updated your SMBIOS on your original config.plist and to also use that information on the new config_install.plist, otherwise the update will fail.
