### ISSUE TITLE
关于7月6日更新版本使用反馈

### ISSUE THREAD

**Issue by fenglinnet** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#34]
我的机器是8750H，4K屏幕版本。前天更新到了7月6日的版本，对比之前4月21日的版本，机器发热明显提升，风扇噪音明显变大。同时，使用iStat Menus 显示温度会发现有时负载比较大时，温度会一直显示5，60度，维持几分种后才升到8，90度。

昨天恢复到7月5日的版本后，问题消失。使用体验和4月21日的版本接近，iStat Menus显示也正常了。

**Comment by LuletterSoul** [comment]
是否将原clover删除干净再复制；是否清空了缓存，是否尝试过生成CPUFriend替换

**Comment by fenglinnet** [comment]
重建缓存后温度下来了。不过，高负载时风扇噪音比原来版本要大一些，估计是对温度更敏感导致。最后，使用7月6日更新版本，把VirtualSMC替换成FakeSMC，使用体验和之前版本类似。
