### ISSUE TITLE
"Service exited with abnormal code: 1" for "org.ntp.sntp.179".

### ISSUE THREAD

**Issue by mutulong** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#35]
I am stuck here every single time, I have tried your config.plist as well as bavariancake's, both are not working for me, can anyone shed some lights what I did wrong.

![IMG_1892](https://user-images.githubusercontent.com/366743/61173439-bf257c00-a5d6-11e9-8824-9f29dd4fd835.jpg)

**Comment by LuletterSoul** [comment]
Did you finish Mojave installation firstly? Which `config.plist` do you use?

**Comment by mutulong** [comment]
It was actually caused by a Broadcom DW 1820A card I replaced for the Killer card, all good now, I managed sorted it out.

**Comment by LuletterSoul** [comment]
@mutulong Thanks, bro. Close it now.
