### ISSUE TITLE
DW1830 启动非常慢后蓝牙关闭

### ISSUE THREAD

**Issue by manuelnyc** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#37]
我有这个问题，我打开电脑，有时，它会延迟大约5分钟开始，当它最终显示桌面时，蓝牙已关闭。
所以我必须重新启动，然后它快速启动，蓝牙再次运行良好。

这是唯一的问题，然后一切都在我的XPS 9570  -  1080上运行良好

**Comment by LuletterSoul** [comment]
最新更新，通过在硬件上屏蔽针脚56、54，可以修复在电池状态睡眠唤醒造成的DW1830蓝牙不可用问题
