### ISSUE TITLE
鼠标垫手势不再起作用（7月21日更新）

### ISSUE THREAD

**Issue by manuelnyc** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#39]
安装新的（7月21日）kexts文件夹后，鼠标垫手势不再起作用。

我遵循的步骤：
 - 我删除了以前的kexts文件夹，并复制了新的kexts文件夹。
 - 替换了config.plist（1080版）

注意：新的kexts文件夹的文件少于以前的版本。

**Comment by LuletterSoul** [comment]
@manuelnyc 把全部文件整体替换进去，手势驱动需要结合新的SSDT文件

**Comment by manuelnyc** [comment]
谢谢，它有效！
 - 我删除了旧的ACPI，drivers64UEFI，Kexts文件夹
 - 我用新文件夹替换了它们

 - 我没有更换OEM，工具和BOOT文件夹，我应该更换它们吗？

**Comment by LuletterSoul** [comment]
不需要
