### ISSUE TITLE
i5-8300安装之后会时不时有点卡顿

### ISSUE THREAD

**Issue by zihaomu** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#40]

**Comment by zihaomu** [comment]
开机会报错，其他正常

**Comment by zihaomu** [comment]
一般开机之后要等几分钟才能流畅运行，一开始会比较卡，不知道大家有没有这个问题？
配置：
i5-8300
512ssd
hd630
16g内存

**Comment by ZhenbPeng** [comment]
请问使用v1.4的clover后开机报错你怎么处理的？我使用时直接报错重启了，现在换回v1.3了，同8300H 4K屏
