### ISSUE TITLE
Problems when using a DisplayPort monitor.

### ISSUE THREAD

**Issue by andresandiah** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#41]
So today i plugged my apollo interface through TB3. The interface has a daisy chain so I always attach a display in the remaining thunderbolt port (a thunderbolt 2 port = display port). But with the recent update it seems to crash the system. When connected the display turns black, and rapdily flickers a yellow stripe before being completely turned to black.

The system recognizes the display as normal, but my laptop display is unusable: even after I unplug the DP monitor from the apollo. The problem remains consistent when plugging the DisplayPort directly to the pc (with an adapter).

This was not a problem with the 1.3 release. Any ideas why this happened?

**Comment by andresandiah** [comment]
![4CE2EFBF-773B-4446-926A-96DE9723DF1B](https://user-images.githubusercontent.com/45172029/61815575-27aefd00-ae10-11e9-99b7-80117c1af0e9.jpeg)

The problem gets worse. After unplugging and restarting the machine. My display now has a brightness flicker in certain areas where it seems that the brightness changes very quick.

**Comment by LuletterSoul** [comment]
Does the recent update you mentioned refer to the update of my repo, or `Mojave 10.14.6` ?

`Mojave 10.14.6` was included a graphic fixed, I don’t know whether it refers to this issue or not.

**Comment by andresandiah** [comment]
i was referring to you your latest repo update.  1.4

**Comment by LuletterSoul** [comment]
It’s really strange.I think I didn’t change anything about graphic output.

**Comment by andresandiah** [comment]
I downgraded the BIOS to the one you recommend on the latest release, and got everything working again. It was my fault; once again, thanks for all the work you put into this EFI!

**Comment by duongle26** [comment]
how could you downgrade BIOS ? Do you have to install windows 10 to re-install the old version of BIOS ?
