### ISSUE TITLE
Installer boots for 2 seconds and shuts down

### ISSUE THREAD

**Issue by carlosxfigueroa** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#42]
I have almost the exact same laptop specs minus the 4K screen, I’m using the config_installer and it keeps shutting down, what can i do?

**Comment by andresandiah** [comment]
make sure you have formatted your drive in the correct format (if your drive is compatible with 4k sectors, format it in that way before installing macOS). Make sure you copied all the correct files to the usb, specially with clover latest update. a few things got moved around. 

if you have a folder called "drivers" then, from the 1.4 zip copy the files inside the "drivers64UEFI" to "drivers/UEFI" folder. check again and let me know if everything is alright.
