### ISSUE TITLE
心急吃了个热豆腐，新Clover +10.14.6事宜

### ISSUE THREAD

**Issue by josangmi** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#43]
新Clover 一直到升级好10.14.6都很正常，可以一直进入到系统，然后重建缓存的时候出现下面的错误：Kext with invalid signatured (-67050) allowed: <OSKext 0x7f9930522d50 [0x7fff8d7038e0]> { URL = "file:///System/Library/Extensions/VoodooI2C.kext/Contents/PlugIns/VoodooI2CServices.kext/", ID = "com.alexandred.VoodooI2CServices" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7f9930519aa0 [0x7fff8d7038e0]> { URL = "file:///System/Library/Extensions/VoodooI2C.kext/Contents/PlugIns/VoodooGPIO.kext/", ID = "org.coolstar.VoodooGPIO" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7f9930516b70 [0x7fff8d7038e0]> { URL = "file:///System/Library/Extensions/VoodooI2C.kext/", ID = "com.alexandred.VoodooI2C" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f9930417c00 [0x7fff8d7038e0]> { URL = "file:///System/Library/Extensions/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Mouse.kext/", ID = "org.rehabman.voodoo.driver.PS2Mouse" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f993040e7e0 [0x7fff8d7038e0]> { URL = "file:///System/Library/Extensions/VoodooPS2Controller.kext/", ID = "org.rehabman.voodoo.driver.PS2Controller" }
但是重启后使用config还是正常进入系统。
其他功能待后续测试。

**Comment by josangmi** [comment]
DA300 的USB HDMI正常，蓝牙正常，屏幕正常。 但是启动超级超级慢，-v模式会卡几个地方，但是最后还是能进到系统。不知道是不是缓存失败的原因。

**Comment by josangmi** [comment]
重新 config_install 也不行，有啥解决办法吗？还是要升级新的clover ，5018的clover的文件目录好像变了好多。

**Comment by LuletterSoul** [comment]
* 正常操作升级，本EFI已支持`10.14.6`

* 请提供-v 卡住地方的日志

* 提供机型信息

**Comment by josangmi** [comment]
用Kext unity 重新把voodoo的两个缓存之后，解决启动慢的问题。硬件配置：
Machine :Dell XPS 9570
CPU: Intel i7-8750H
GPU: UHD630 + Nvidia Gefore 1050Ti(屏蔽)
RAM: 16GB RAM
Display: 4K Sharp Display
SSD: NVMe SAMSUNG 512GB SSD
Audio: Realtek ALC298
Touchscreen
WLAN + Bluetooth : DW1830（已更换）
