### ISSUE TITLE
还是老问题，可以控制风扇吗

### ISSUE THREAD

**Issue by linkjane** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#44]
我现在还是没有风扇控制，然后风扇时快时慢，类似潮汐，有的时候如果cpu占用稍微多点，磁盘读写多点，温度还是49度左右，风扇就一直类似正弦函数的响，极端的情况下，cpu会降频到0.8ghz，电脑卡的不行，我的型号是i9 xps 9570 系统是10.14.5，所以现在能控制风扇吗？

**Comment by LuletterSoul** [comment]
风扇目前无解。另外，你可以测试一下windows下的转速，测试不同版本的BIOS，选择一个最适合的BIOS版本。

**Comment by linkjane** [comment]
好吧，那现在目前只能先这样了
