### ISSUE TITLE
10.14.5使用v1.4EFI 出现panic cpu 0 caller 错误

### ISSUE THREAD

**Issue by ZhenbPeng** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#46]
本机配置
xps15 9570
i5-8300H 4K触摸 32G RAM 256SSD 更换DW1560无线网卡 
bios 1.11.2 MacOS 10.14.5 windows10 1809

在v1.4版EFI release后， 立即换上后发现会自动重启，无法进入系统，在除去lilu输入后得到如下截图。
随机会出现  panic cpu 0 caller ，panic cpu 1 caller， panic cpu 2 caller的错误。
clover boot参数添加keepsysms=1也不行，再删除cpufriend两个kext和voodoo触摸的三个kext，还是一样的现象。  
![IMG_2016](https://user-images.githubusercontent.com/6396884/62002778-277b6e00-b13e-11e9-9463-003b396051d7.JPG)
![IMG_2014](https://user-images.githubusercontent.com/6396884/62002779-2b0ef500-b13e-11e9-9de7-7aed154df8ae.JPG)
![IMG_2013](https://user-images.githubusercontent.com/6396884/62002780-2fd3a900-b13e-11e9-958e-f6e87e1b721b.JPG)

**Comment by LuletterSoul** [comment]
日志显示你在使用 `2.1.6` 版本的触摸板驱动，而最新的EFI使用的是`2.2`

很有可能是缓存没清理干净

用`-x` 进入安全模式，用`Kext Utility`重建缓存再尝试进入系统

如果依旧没法进入，在Clover界面按`F11`清空`NVRAM`

**Comment by ZhenbPeng** [comment]
经你提醒，查看了下s/l/e下的目录，发现有三个触摸驱动在那里，是以前去掉-v模式时加入的。
把这三个驱动删除，立马就可以进入系统了。
v1.4版解决了很多问题呀。
task的高占用没有了，美滋滋
谢谢大佬的无私分享与解答
