### ISSUE TITLE
2 fingers click is broken

### ISSUE THREAD

**Issue by Herna1994** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#5]
After you added the advanced gestures, double click doesn't work anymore. I have tried setting it to only click on bottom right/left part and still not working.

**Comment by LuletterSoul** [comment]
It works fine for me.Rebuild kextcache before you change EFI.

**Comment by Herna1994** [comment]
I installed all the required kexts using KextBeast and then did then rebuilt kextcache.

Maybe I wrote it bad, I was meaning the secondary click, doesn't work here. 

I have everything working but the two click, gestures and all work awesomely.

I also tried to delete the Voodoo stuff, and without it the secondary click works fine except gestures.

**Comment by Herna1994** [comment]
I have tried again to do everything from scratch, and still not working as desired. Two click is completely broken, doesn't work on any of its 3 forms.

**Comment by Herna1994** [comment]
Fixed by updating VoodooI2C to 2.1.5 version.
