### ISSUE TITLE
睡眠有一定几率出现wake sleep transition的内核崩溃

### ISSUE THREAD

**Issue by M69W** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#50]
[睡眠有一定几率出现wake sleep transition的内核崩溃](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98)

尝试拔开电源再合盖，
睡眠后这个问题貌似可以解决。

显然这不是最优解，但找不到原因

不过官方好几次更新说明系统存在睡眠问题：
https://twitter.com/tualatrix/status/1159036274574950402/photo/1
https://pbs.twimg.com/media/EBW5VlzUYAEjmN6?format=jpg&name=large

设备：
i5-8300h，1080P

**Comment by andresandiah** [comment]
You can install it using your USB to boot and using config_install.plist

**Comment by LuletterSoul** [comment]
在睡眠过程中，理论上配置的热补丁已经给所有USB断电，但还是出现了USB驱动造成的睡眠过程中断；

建议大家使用戴尔自带FN + Insert睡眠键进入睡眠S3状态，该模式任何设备无法终止睡眠过程直到完成。目前为止我没遇到过这个BUG

**Comment by LuletterSoul** [comment]
到Catalina 10.15为止，这个睡眠问题再也没有出现过。

**Comment by M69W** [comment]
目前使用 [OC](https://github.com/xxxzc/xps15-9570-macos)了,暂时无此问题

**Comment by wtdcode** [comment]
我更新了BIOS后突然频繁出现这个问题了。。。。。
