### ISSUE TITLE
Laptop's Display is not working when connected to External Display via USB-C(TB)

### ISSUE THREAD

**Issue by duongleh** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#52]
Hello, 
Firstly, I want so say thank you for the great work on this repo!

Currently I am unable to get external displays to work properly with my Dell XPS 15 9570. My laptop' specs are:
BIOS: 1.12.0
MacOS: 10.14.6
Core i7 8750H
Intel UHD 630 Graphics
8GB DDR4
1080p
External display: Dell U2419HC

The issue is that OS detects the display, the external display lights up but laptop's display is blackout.

Please let me know what information I can provide to try and help get this resolved.
Thank you very much.

![Screen Shot 2019-08-10 at 10 19 43 PM](https://user-images.githubusercontent.com/28813618/62823650-5ae9de00-bbbd-11e9-8d33-62e00f211b46.png)

![20190810_222001](https://user-images.githubusercontent.com/28813618/62823672-a13f3d00-bbbd-11e9-8e20-86e114f65e8f.jpg)

**Comment by andresandiah** [comment]
i had this issue too. The latest releases are based on BIOS 1.11.2, NOT 1.12.0.
Downgrade your BIOS version and it should go back to normal operation

**Comment by duongleh** [comment]
> i had this issue too. The latest releases are based on BIOS 1.11.2, NOT 1.12.0.
> Downgrade your BIOS version and it should go back to normal operation

thanks for your solution. Don't know when LuletterSoul releases version based on BIOS 1.12

**Comment by duongleh** [comment]
I downgraded the BIOS to the one recommend on the latest release, and got everything working again. Follow this guide to flash the BIOS https://www.dell.com/support/article/vn/en/vndhs1/sln305230/flashing-the-bios-from-the-f12-one-time-boot-menu?lang=en
Thanks once again !
