### ISSUE TITLE
1080p钙版死机问题

### ISSUE THREAD

**Issue by epnode** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#53]
无法使用config_install.plist安装系统，使用confug_1080P.plist或config.plist可以进入安装界面但会随机死机
config_install.plist报错为
Forcing CS_RUNTIME for entitlement: com.apple.rootless.install
BIOS版本为1.11.2 硬盘更换为SM961(惠普批次，在台式机上黑苹果正常) 网卡为DW1830(已屏蔽针脚)

**Comment by epnode** [comment]
问题为DW1830所致，但是不知道如何解决，网卡是以前9550上拆下的

**Comment by epnode** [comment]
ASL Module "com.apple.mkb" sharing output destination "/private/var/log/keybagd.log" with ASL Module "com.apple.mkb.internal".
	Output parameters from ASL Module "com.apple.mkb.internal" override any specified in ASL Module "com.apple.mkb".
Aug 13 00:30:00 epmandeMBP syslogd[38]: Configuration Notice:
	ASL Module "com.apple.mkb" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 13 00:30:00 epmandeMBP syslogd[38]: Configuration Notice:
	ASL Module "com.apple.AddressBookLegacy" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 13 00:30:00 epmandeMBP syslogd[38]: Configuration Notice:
	ASL Module "com.apple.MessageTracer" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 13 00:30:00 epmandeMBP syslogd[38]: Configuration Notice:
	ASL Module "com.apple.networking.boringssl" sharing output destination "/Library/Logs/CrashReporter" with ASL Module "com.apple.networking.networkextension".
	Output parameters from ASL Module "com.apple.networking.networkextension" override any specified in ASL Module "com.apple.networking.boringssl".
Aug 13 00:30:00 epmandeMBP syslogd[38]: Configuration Notice:
	ASL Module "com.apple.clouddocs" claims selected messages.
	Those messages may not appear in standard system log files or in the ASL database.
Aug 13 00:30:03 epmandeMBP com.apple.xpc.launchd[1] (com.apple.mdworker.shared.06000000-0000-0000-0000-000000000000): Service only ran for 3 seconds. Pushing respawn out by 7 seconds.
Aug 13 00:30:03 epmandeMBP com.apple.xpc.launchd[1] (com.apple.mdworker.shared.05000000-0000-0000-0000-000000000000): Service only ran for 3 seconds. Pushing respawn out by 7 seconds.
Aug 13 00:30:03 epmandeMBP com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0000-0000-0000-000000000000): Service only ran for 3 seconds. Pushing respawn out by 7 seconds.
Aug 13 00:30:03 epmandeMBP com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0E000000-0000-0000-0000-000000000000): Service only ran for 3 seconds. Pushing respawn out by 7 seconds.
Aug 13 00:31:42 epmandeMBP com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Aug 13 00:32:55 epmandeMBP com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Aug 13 00:33:27 epmandeMBP appstoreagent[548]: objc[548]: Class ASDPurchaseResult is implemented in both /System/Library/PrivateFrameworks/AppStoreDaemon.framework/Versions/A/AppStoreDaemon (0x7fff94706be8) and /System/Library/PrivateFrameworks/AppStoreDaemon.framework/Support/appstoreagent (0x10229ad40). One of the two will be used. Which one is undefined.
Aug 13 00:33:39 epmandeMBP com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Aug 13 00:34:55 epmandeMBP com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Aug 13 00:40:37 epmandeMBP syslogd[38]: ASL Sender Statistics
Aug 13 00:49:47 epmandeMBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.user.501): Service "com.apple.xpc.launchd.unmanaged.loginwindow.87" tried to register for endpoint "com.apple.tsm.uiserver" already registered by owner: com.apple.SystemUIServer.agent
Aug 13 00:50:17 --- last message repeated 1 time ---

**Comment by epnode** [comment]
Process:               com.apple.preference.network.remoteservice [507]
Path:                  /System/Library/PreferencePanes/Network.prefPane/Contents/XPCServices/com.apple.preference.network.remoteservice.xpc/Contents/MacOS/com.apple.preference.network.remoteservice
Identifier:            com.apple.preference.network.remoteservice
Version:               1.0 (1.0)
Build Info:            NetworkPref-444000000000000~925
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           System Preferences [466]
User ID:               501

Date/Time:             2019-08-12 05:20:32.113 -0700
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Anonymous UUID:        71B6CB89-4FEC-4BFE-1165-E9CF643F7E69

Sleep/Wake UUID:       E8CE0E7F-1123-46D7-89FF-D0290C7B00A3

Time Awake Since Boot: 310 seconds
Time Since Wake:       810 seconds

System Integrity Protection: disabled

**Comment by duongleh** [comment]
I got the same problem using v1.5, had to switch to v1.4. My wifi card is DW1560

**Comment by epnode** [comment]
Xigtun/xps-9570-mojave#26

done.I will close this issuse.
