### ISSUE TITLE
VodooI2CController problem

### ISSUE THREAD

**Issue by FrenkyBojler** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#56]
Hi guys,
trying to install Mojave on my Dell Inspiron 7386:
- i7-8565U
- 16GB RAM
- 256GB SSD Hynix
- Intel UHD 620

I got stuck on:
![69240293_2755077257859622_4388444712281833472_n](https://user-images.githubusercontent.com/14737925/63279391-82504300-c26e-11e9-99eb-1cd49c9f44e7.jpg)

Kexts:
![Screen Shot 2019-08-19 at 09 10 33](https://user-images.githubusercontent.com/14737925/63279452-9dbb4e00-c26e-11e9-9535-f1d97c8cf1ee.png)

I would appreciate any help.
Thanks.

**Comment by LuletterSoul** [comment]
@FrenkyBojler 
Hi, you can remove `SSDT-I2C.xml` and try it again.
