### ISSUE TITLE
有完整敎學嗎？

### ISSUE THREAD

**Issue by carlhung** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#57]
我從沒用過黑蘋果。
我現在是windows/Linux,怎樣加入黑蘋果？

**Comment by luvu4evermore** [comment]
建议善用 Google. 本人从从没用过到现在已经装好用起来只用了一晚上。。。。

**Comment by tuotuoZ** [comment]
> 我從沒用過黑蘋果。
> 我現在是windows/Linux,怎樣加入黑蘋果？

https://www.youtube.com/watch?v=h22MJD8C1r8&t=185s
可以看看这个人的

**Comment by LuletterSoul** [comment]
@tuotuoZ 
谢谢你提供的资源，这位朋友做的安装向导特别好。
