### ISSUE TITLE
启动慢，没有蓝牙，我已经在dw1830上放了磁带

### ISSUE THREAD

**Issue by manuelnyc** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#58]
@LuletterSoul 

在dw1830上，将磁带放在引脚54和56上不起作用......有时候计算机启动速度非常慢，3或4分钟，并且没有蓝牙，所以我必须重新启动，也许它启动很快或者它可能是 将再次开始缓慢。

此外，睡觉后，没有w.i.f.i.

检查视频
https://youtu.be/z7HYxlIjpi0

Mojave 10.14.5
Dell XPS 9570 - 1080

**Comment by LuletterSoul** [comment]
@manuelnyc 
Hi, please provide `-v` panic log when open issue.
