### ISSUE TITLE
想知道用什么方案禁用的触摸屏

### ISSUE THREAD

**Issue by feiyunroc** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#59]
rt，因为本人4k屏没有接上触摸部分，想取消禁用看看有啥变化

**Comment by tofuliang** [comment]
BIOS可以设置的

**Comment by LuletterSoul** [comment]
如果你用的是Mojave，可以用1.5之前的版本尝试；如果你用的是Catalina，可以用1.5之前的版本，然后更新Luli、WEG、蓝牙驱动尝试。

**Comment by LuletterSoul** [comment]
如果你用的是Mojave，可以用1.5之前的版本尝试；如果你用的是Catalina，可以用1.5之前的版本，然后更新Luli、WEG、蓝牙驱动尝试。
