### ISSUE TITLE
[FIX] Coffee Lake Intel UHD Graphics 630 on macOS Mojave: HDMI Output Issue [Public Testing Stage]

### ISSUE THREAD

**Issue by LuletterSoul** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#6]
[[FIX] Coffee Lake Intel UHD Graphics 630 on macOS Mojave: HDMI Output Issue [Public Testing Stage]](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-output-issue-public-testing-stage.275126/)

该方案在本人机器上得到解决，但依旧需要更多测试，请各位遇到问题的朋友在该issue下反馈，并附上机器配置。

**Comment by 0xFireWolf** [comment]
Stage 2 is now available. The new fix now supports HDMI 2.0 hotplug after the system boots.

Please carefully read the [original thread](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-output-issue-public-testing-stage.275126/) and post your test results **under the original thread**.

**Comment by wtdcode** [comment]
[这里](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#%E4%BF%AE%E5%A4%8Dhdmi%E8%BE%93%E5%87%BA) 是用 Hackintool 做的 patch 吗，请问是怎么patch的？

**Comment by zealforbeing** [comment]
能说说具体咋做吗？我mojave 10.14.5 UHD630核显HDMI2.0输出紫屏。

**Comment by 0xFireWolf** [comment]
Public testing closed. WhateverGreen 1.3.0 now contains this fix. Please carefully read the manual ([EN](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md), [CN](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.cn.md)) before you get started. Thank you for participating the test. : )

**Comment by LuletterSoul** [comment]
@0xFireWolf 
Thanks so much! You have provided a great and more general fix solution for many machines with Coffe Lake.  

 In the [previous testing job](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-1-4-2-0-output-issue.275126/post-1956373), I posted a feedback:  when the 4k@60Hz monitor's  mode is set to 1080p@60hz HDpi, I put the system to sleep and then wake it up, the monitor would lose its signal. After switching its mode to 1080p@30hz HDpi, the display was lit up again.

After updating WEG 1.3.0, I conducted dozens of tests again, but the situation is still the same.

I delved into the source code of your PR in WEG and found that the driver has a logic in the function `framebufferSetupLPSCON()` in which the LPSCON driver is only initialized once. After probing LPSCON, the driver changes the register value, and then the current driver object will be cached. When the system wakes up, the `framebufferSetupLPSCON()` is called again, but since the kernel thinks that the LPSCON driver has been initialized, it will not perform subsequent  work to change LPSCON state, only executing `wakeUpNativeAUX` once (from the system log, this operation returns the wrong kernel value `RV = 0xe00002d6`)
<img width="768" alt="Screen Shot 2019-07-06 at 4 10 20 PM" src="https://user-images.githubusercontent.com/21377419/60753647-96b2e600-a008-11e9-9306-df7853c19321.png">


Why the function input register address with `0x00000`？I really feel confused here.

<img width="741" alt="Screen Shot 2019-07-06 at 3 37 27 PM" src="https://user-images.githubusercontent.com/21377419/60753387-0a9ebf80-a004-11e9-8c2b-92d0b54a4d88.png">


In my XPS, this logic seems to have no effect on the LPSCON adapter.
I guess it should be that the LPSCON register is reset to its default state after the system sleeps and wakes up. If the kernel does not configure LPSCON adapter to make it work in PCON mode , it will keep the default state(maybe LS mode I guess..), the HDMI output rate will not reach the maximum, so 1080P@60hz HDpi output is not enough naturally.

Therefore, I comment the code that make the driver only initialize once, as below:

<img width="1293" alt="Screen Shot 2019-07-06 at 3 19 03 PM" src="https://user-images.githubusercontent.com/21377419/60753363-a845bf00-a003-11e9-907a-44e4904072ab.png">


To make kernel create the driver object and set mode of LPSCON to PCON every time `framebufferSetupLPSCON()` is called. The experiment proves that I fixed the issue posted in the previous content.The HDMI 2.0 port works fine now even if I put the system to sleep and wake it up.

Building a driver object cache is definitely correct. The bad influence of my method should be that the kernel will cause the overhead for constant driver object creation. I can't confirm whether LPSCON is reset after sleep and wake up, or whether there is a bug when kernel caches the driver object, but this probe-every-time mehod is really work for me.

I hope this feedback will help the driver improvement.

**Comment by 0xFireWolf** [comment]
@LuletterSoul Thanks for your feedback.   

Yes, your thought is generally correct. LSPCON adapter on Dell XPS 15 9570 is switched back to LS mode when its power is off, and I forgot to merge the fix for it.  

I will fix this issue soon. : )

**Comment by 0xFireWolf** [comment]
@LuletterSoul Fixed. Commit at [here](https://github.com/0xFireWolf/WhateverGreen/commit/4fed192a36a7d42fc054aac4d954704273d82ae0); Waiting for the [PR](https://github.com/acidanthera/WhateverGreen/pull/27) to be merged. Please compile the latest code and the issue should now be fixed.

**Comment by LuletterSoul** [comment]
@0xFireWolf Great! Now the HDMI 2.0 port work fine now using latest build ,which is much better than what I modify roughtly in your previous code ,hahah~

I think this issue has been fixed completely until now.Closed.

**Comment by wtdcode** [comment]
Excellent works!
Many thanks to @LuletterSoul and @0xFireWolf.
