### ISSUE TITLE
网卡DW1820A

### ISSUE THREAD

**Issue by fieldxy** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#61]
经测试DW1820A目前可以使用，wifi，蓝牙，airport 都能正常使用，不过目前还在测试中看看稳不稳定

**Comment by tcstory** [comment]
需要处理那个第三根天线的问题吗?

**Comment by Ahian** [comment]
> 经测试DW1820A目前可以使用，wifi，蓝牙，airport 都能正常使用，不过目前还在测试中看看稳不稳定

测试得怎么样了？我用dw1820a会卡死

**Comment by fieldxy** [comment]
只有两根天线，DW1830 有三根线

**Comment by fieldxy** [comment]
目前没遇到什么特殊的问题 但是长时间关机重新开机，WiFi 需要等待一会 才能自动连接 
需要屏蔽引脚

**Comment by stingzhan** [comment]
> 目前没遇到什么特殊的问题 但是长时间关机重新开机，WiFi 需要等待一会 才能自动连接
> 需要屏蔽引脚

我更换后出现了睡眠无法唤醒的问题，请问你有遇到类似的情况吗

**Comment by fieldxy** [comment]
没有遇到过……
