### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by napster93** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#64]
Hi All,

I am trying to install Mojave on my xps 9570. I have copied the EFI folder from this repo and managed to get the system booted up to installation screen. But everytime my laptop keep restarting when the remaining time reaches 12 minutes. 

Can you please help me out here. I am a newbie to Hackintosh as well

**Comment by napster93** [comment]
All good. Found out my ssd is not compatible. Got everything sorted. PM981 NVMe Samsung 500GB didnt work in dell XPS 15 9570.

**Comment by RumenTech** [comment]
@napster93 

I'm trying to install Mojave on my xps 7590.
- Do you know if `NVMe Micron 2200S NVM` is an eligible SSD for hackintosh?
- Where can I find the list of supported SSDs?
- In BIOS, do you set SATA to "AHCI" or "Raid On"?

**Comment by attilagyorffy** [comment]
> @napster93
> 
> I'm trying to install Mojave on my xps 7590.
> 
> * Do you know if `NVMe Micron 2200S NVM` is an eligible SSD for hackintosh?
> * Where can I find the list of supported SSDs?
> * In BIOS, do you set SATA to "AHCI" or "Raid On"?

Hi @RumenTech, you can find a [list of supported SSDs on the tonymacx86 buyers guide](https://www.tonymacx86.com/buyersguide/building-a-customac-hackintosh-the-ultimate-buyers-guide/#Solid_State_Drives). For the Micron 22005 specifically I couldn't find any information so far. I recommend swapping out your drive with something that has fairly wide support by hackintosh users. I went with the Samsung 970 EVO and had no issues whatsoever. Install went smooth without any kind of hackery. (For the record, the install had intermittent kernel paics until I've swapped out my Samsung PM981 NVMe, just like @napster93)

For the SSD to work properly and being picked up, you'd have to use AHCI. Good luck!

**Comment by RumenTech** [comment]
@attilagyorffy Thanks for your information! But I'm afraid I can't spend additional cost for replacing with another SSD.

**Comment by cheng10** [comment]
> * Micron 2200S

 Micron 2200S is not suppprted for hackintosh. check out here:
https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html
