### ISSUE TITLE
Can anybody record a video about xps9570 stylus pen on touchscreen?

### ISSUE THREAD

**Issue by Jamesxxx1997** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#66]
Hi , everyone.
I'm interested in xps9570 touchscreen version ; however , there seems to have some issue about 9570 i2c touchscreen.
Can anybody record a video to show how stylus pen work under macos , and post it to youtube?
Thanks.

**Comment by LuletterSoul** [comment]
It is a charming feature, everyone will be excited if someone make it.But no related solution has been post so far.Please tell me here if you find a better routine.
