### ISSUE TITLE
电量显示不精确

### ISSUE THREAD

**Issue by umiotter** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#67]
可能是我的是97W电池的缘故,充满电之后掉电特别快大约4~5个小时电量就显示成0%了,但是变成0%之后还是能使用3个小时左右

**Comment by seanxu01** [comment]
> 可能是我的是97W电池的缘故,充满电之后掉电特别快大约4~5个小时电量就显示成0%了,但是变成0%之后还是能使用3个小时左右

解决了吗

**Comment by carlosxfigueroa** [comment]
how did you solve the issue?

**Comment by LuletterSoul** [comment]
请问这位朋友的机型是1080P吗，能达到8个小时的续航是惊人的。
