### ISSUE TITLE
Is there anyone update to Catalina successfully?

### ISSUE THREAD

**Issue by mushanshanshan** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#69]
I want to extend my laptop with an iPad.

**Comment by erenatas** [comment]
I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.

**Comment by mushanshanshan** [comment]
Thanks!

> I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.

**Comment by yongjiajun** [comment]
> Thanks!
> 
> > I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.

更新成功吗？

**Comment by mushanshanshan** [comment]
> > Thanks!
> > > I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.
> 
> 更新成功吗？

需要更新一下clover，wifi和蓝牙驱动，其他没有大问题

**Comment by chinmayjade** [comment]
> I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.

I'm not sure how to exactly do this. Can you post a short procedure? I have Hackintool downloaded.

**Comment by erenatas** [comment]
> > I tried it before. I updated my clover, kexts, etc. by checking it with hackintool and then gave it a shot. It worked.
> 
> I'm not sure how to exactly do this. Can you post a short procedure? I have Hackintool downloaded.

Check your installed kexts if they are on latest version. Then upgrade directly. That's should be enough. But honestly Mojave seemed better back when I tried.

**Comment by LuletterSoul** [comment]
It works definitely on masOS Catalina.
