### ISSUE TITLE
Mojave 10.14.4

### ISSUE THREAD

**Issue by erenatas** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#7]
Hi there, thanks a lot for your configuration! 

With the 10.14.4 Mojave image, I tried to install hackintosh on my 9570 but unfortunately I couldn't get graphics accelerator to work. As you have written, I have used config_install during installation and after booting with config_install, I have done: \
```sudo kextcache -i /``` \

When I try to boot with ```config_10.14.4.plist``` it panics after initializing iGPU. Lines are written too fast so I cannot read what it is.

When I try to boot with ```config.plist``` it gets stuck at:
```busy timeout[0], (60s): 'AppleMultiTouchDevice', 'AppleMultitouchDevice'```

Would love to hear what I can do to fix this problem! Cheers!

**Comment by LuletterSoul** [comment]
First of all, thank you for being able to test config_10.14.4.plist. It's a test config only .After upgrading to 10.14.4, I also encountered the same fatal error. Therefore, if you need stability, I suggest you stay at 10.14.3. When I have free time, I will improve it's performance at 10.14.4. Best wishes,my friend.

**Comment by erenatas** [comment]
I am trying to use 10.14.3 right now. As you may know, it's not so easy to find it on the internet. Thank you for your effort!

**Comment by dhruvdangi** [comment]
I will be receiving my laptop in a week or so, was planning to try 10.14.4 but I guess I will have to stick to 10.14.3
@erenatas Can you share the download link of 10.14.3 setup, I'm not able to find it anywhere online.

**Comment by erenatas** [comment]
> I will be receiving my laptop in a week or so, was planning to try 10.14.4 but I guess I will have to stick to 10.14.3
> @erenatas Can you share the download link of 10.14.3 setup, I'm not able to find it anywhere online.

You can get it here.

https://miroir1.trackr.fr/download.php?file=https://miroir1.trackr.fr/macOS_10.14.3Final/Install.macOS.Mojave.app.zip&source=mac

**Comment by dhruvdangi** [comment]
@erenatas Thanks for the link, I've tried downloading it 4 times but it stops downloading once 5.37GB is downloaded.

**Comment by erenatas** [comment]
@dhruvdangi I had the same issue, I started another one, then resumed the stopped one. Then stopped the second download that I have started.

**Comment by tofuliang** [comment]
> @erenatas Thanks for the link, I've tried downloading it 4 times but it stops downloading once 5.37GB is downloaded.

Here is 10.14.3 downloaded with [macOS Mojave Patcher](http://dosdude1.com/mojave/#downloads)

`https://pan.baidu.com/s/11w4QcqDViML7VfKowo1ZBg`  with Pass `mmj6`

**Comment by erenatas** [comment]
Managed to make 10.14.4 work. Also touch screen gestures are working. Will do some tests and send a pull request if you want.

The hardest part was screen sleep.

@LuletterSoul How did you make GPU vram 2G? Mine is at 1536M right now but I don't really know why it is..

**Comment by LuletterSoul** [comment]
@erenatas 
Thank you for your in-depth testing work！Would you do more testing about following parts?

* Sleep : Sleep and wake up ,screen should be light.
* Backlight: Backlight should be normal no matter reboot , or wake up from sleep.And it could be adjusted via F11 or F12
* HDMI: Graphics Acceleration: UHD630 could drive the 4k panels.
* New modification shouldn't affect the HDMI output, fixed in this version.
* Audio: Original sound card should work fine.
* No panics: There should be almost no panics when machine running.

If you pass all tests above ,please send a PR if you are convenient. I will review what you changes and merge into my repository for further testing!

At last,varm is redefined via Devices/Properties entry `framebuffer-unifiedmem` by `WhateverGreen`.

**Comment by erenatas** [comment]
I have to work today but in the worst case, I will open the pull request by tomorrow if everything is alright

**Comment by erenatas** [comment]
Update: Sleep and Audio is fine but I just managed to try HDMI and it panicked. It's not really my priority right now. I will try to make iGPU 2048M first.

**Comment by erenatas** [comment]
Sent pull request:

https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/pull/10

**Comment by LuletterSoul** [comment]
@erenatas  Thanks for your hard testing work!
As far as I know , the changes you make in PR are almost unnecessary. Mojave 10.14.4 should work now when I just changed one item, I made a mistake before.Please see my
newest commit history.
