### ISSUE TITLE
触摸板响应速度优化方案

### ISSUE THREAD

**Issue by geek5nan** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#70]
[VoodooI2CHID.kext/Contents/Info.plist](https://github.com/alexandred/VoodooI2CHID/blob/841bd6c7806e92cf215dbfe27f9eacb6e1b7ce4b/VoodooI2CHID/Info.plist) 中的 `QuietTimeAfterTyping`  字段是用来控制 I2C 触摸板在内置键盘事件后的静默时间，默认时间为 500 ms。因此在按键抬起的 500 ms 内，I2C 将忽略来自触摸板的事件，以防打字时误触触摸板引起光标漂移的情况。
但在一些特殊场景下（如 CapsLock、Cmd + Tab 等功能键），500 ms 则会给人明显的阻塞感。
若要解决这个问题，可将 **EFI/CLOVER/kexts/Other/VoodooI2CHID.kext/Contents/Info.plist** 中 `QuietTimeAfterTyping` 字段的值改小一些来减少触摸板静默时间，提高触摸板响应速度。

**Comment by geek5nan** [comment]
顺便说一下，默认的 500 ms 相当于 30 帧，而触屏手机的刷新率通常为 60 帧 / 每秒，所以此处 30 帧的延迟会给人明显的卡顿感。
此值也并非越低越好。若将其设置为 0 的话，则打字时发生触摸板误触的机率会很高，从而造成输入光标漂移、文字错位等小问题影响输入体验。
修改时应**以打字时不发生误触；打字后触摸板无明显延迟**为标准。依据我个人的习惯，将此值设置在 7 ~ 10 帧之间即 120 ~ 170 ms 之间体验都还不错。

**Comment by mceykes** [comment]
did this also fix trackpad lag for you, or did you not encounter this problem? Thanks!

**Comment by geek5nan** [comment]
> did this also fix trackpad lag for you, or did you not encounter this problem? Thanks!

If `QuietTimeAfterTyping` is set to 0, there will be no lag anymore.
By the way, when `QuietTimeAfterTyping` is set to 0, typing on the built-in keyboard may be interrupted, so it is recommended to set it to 120 ~ 170, depending on your habits.

**Comment by M69W** [comment]
实测有效，
默认 QuietTimeAfterTyping 为0，改为120
重启有效：
一边打字，同时滑动触摸板，可以检测结果

**Comment by LuletterSoul** [comment]
@geek5nan 
首先，非常感谢您的优化方案，我会在以后的版本中将您的方案整理到问题集锦中。我先关闭此问题，如果后续有优化可以继续开启。
