### ISSUE TITLE
你什么时候更新下oc引导的efi？

### ISSUE THREAD

**Issue by ghost** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#74]
我现在用的oc引导 是clover移植过来的 显卡补丁也是照搬过来，但是发现外接显示器为30hz
<img width="488" alt="屏幕快照 2019-11-04 下午22 49 22 下午" src="https://user-images.githubusercontent.com/52182374/68129928-6d25af00-ff55-11e9-91c3-8c9242c732fd.png">

**Comment by carlosxfigueroa** [comment]
can you upload your efi for opencore?

**Comment by ghost** [comment]
no

**Comment by OldDream** [comment]
> can you upload your efi for opencore?

check this ,basically a OC version os this repository.
https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave

**Comment by M69W** [comment]
CLOVER
https://github.com/bavariancake/XPS9570-macOS
https://github.com/Xigtun/xps-9570-mojave
https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave
https://github.com/smallssnow/XPS9570-8570H-macos
https://github.com/AnneviLL/xps15-9570-hackintosh-EFI

OC
https://github.com/xxxzc/xps15-9570-macos
https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave

**Comment by M69W** [comment]
> 我现在用的oc引导 是clover移植过来的 显卡补丁也是照搬过来，但是发现外接显示器为30hz
> <img alt="屏幕快照 2019-11-04 下午22 49 22 下午" width="488" src="https://user-images.githubusercontent.com/52182374/68129928-6d25af00-ff55-11e9-91c3-8c9242c732fd.png">

闲鱼上卖多少钱了，亲自配置的OC

**Comment by LuletterSoul** [comment]
本仓库只维护基于Clover的稳定配置，想要尝鲜可右拐至[xxxzc](https://github.com/xxxzc/xps15-9570-macos)朋友维护的基于oc的配置。
