### ISSUE TITLE
Audio no longer works after sleep 10.15.1

### ISSUE THREAD

**Issue by carlosxfigueroa** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#75]
after sleeping all night I woke up the laptop and the sound no longer worked, mac os couldnt see the internal speakers

**Comment by erenatas** [comment]
Does your laptop sleep when you close your lid? Mine does not, but it sleeps when I press on sleep button or if I wait for it to sleep when lid is open.

**Comment by aliyektaie** [comment]
I have the same issue with 10.15.1. I'm a bluetooth headset to be able to use my laptop's audio.
Note: I tried Apple's AirPods but they don't work after sleep, just like the 3.5 headphone jack.

**Comment by khoa-nv** [comment]
Yes, I have the same problem and I found a way to solve this problem: Go to Input Settings in `System Preferences => Sound => Input` and keep this window open. when you are using your laptop. Still waiting for someone with a better solution.

**Comment by LuletterSoul** [comment]
CombJack may fix this.See [issues.md 4th](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/blob/master/doc/issues.md)
