### ISSUE TITLE
Enabling HIDPI extra resolutions

### ISSUE THREAD

**Issue by romancin** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#79]
Hi! First if all thank you very much for your work. It is working flawlessly for 7590 4k model. One question, is It possible to enable more HIDPI resolutions for the internal screen like a real MBP? I think 1440p is the best for 15 inch screens, but the maximum available with your EFI folder is only 1080p HIDPI. Thank you!

**Comment by LuletterSoul** [comment]
RDM tool may be helpful for you.
