### ISSUE TITLE
CPU maxes out on it's own

### ISSUE THREAD

**Issue by erenatas** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#8]
I wanted to make sure before opening an issue. I would like to mention that I do have the same laptop with same specs, only that I am using a USB WiFi module because my dw1830 didn't arrive yet. 

I can reproduce this problem after waking up from sleep and sometimes it happens on its own. 

Detailed description: CPU is maxed out on frequency and therefore wattage rises from 3-4W to 14-15W while doing nothing. After waking up from sleep it is around 18-20W on me. Here is a screenshot for proof:

![](https://i.ibb.co/SP6wjJd/Screen-Shot-2019-04-16-at-23-02-57.png)

I really would like to find a solution to this problem. If we can solve it, we could probably have around 6hours of lightweight work battery life.

Cheers

**Comment by chenjh-8** [comment]
I had the same issue,I also use a USB WLAN .

**Comment by erenatas** [comment]
I do not believe it is related to usb WiFi though. I will try to do more tests today.

**Comment by LuletterSoul** [comment]
First, I have around 2.5hours of heavyweight work battery like when I run tens of Chrome tab pages,IDE.etc. I am frustrated because of short time of usage without AC power. Intel Turbo Boost seems to work properly on my machine.It is really nice if I get 6hours battery life,
but it's hard due to we have no battery saving mode on Windows I guess.

You can check whether it's related to usb WIFI device or not by disabling it.

**Comment by erenatas** [comment]
@LuletterSoul  This problem might be related to this ticket:

https://github.com/the-darkvoid/XPS9360-macOS/issues/44

As far as I know, we cannot control fans through HWMonitor, I don't know what LPC is but it might be related to this problem.

**Comment by erenatas** [comment]
Update: This problem may only be appearing on battery.

While using on Battery:
1. Sleep
2. Wakeup -> Kernel_task is at 100% and eating 20W.

While plugged in:
1. Sleep
2. Wakeup -> Kernel_task is how it needs to be. Eating 3-4W

An interesting case (Tried it twice)
1. Plug it out
2. Sleep
3. Wakeup -> Kernel_task is at 100% and eating 20W.
4. Plug it in
5. Sleep
6. Wakeup -> Kernel_task is back to how it should have been. Eating 3-4W once again.

Seriously, what's going on...

**Comment by LuletterSoul** [comment]
@erenatas
I cannot reproduce this weried problem.CPU frequency and power consumption seems to perform normally.
<img width="468" alt="Screen Shot 2019-04-17 at 10 27 23 PM" src="https://user-images.githubusercontent.com/21377419/56296061-5a39c180-6160-11e9-81da-cd2d77159439.png">
<img width="905" alt="Screen Shot 2019-04-17 at 10 27 26 PM" src="https://user-images.githubusercontent.com/21377419/56296065-5c038500-6160-11e9-9e8e-96f212d74e40.png">

As far as I know,AppleLPC is no longer needed  after 6th gen CPU.You can modify [SSDT-LPC.aml](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-LPC.dsl) and 
 make it work.But I don't sure whether it's related to LPC or not.It will be very appreciated if you can do a little for this research.

**Comment by erenatas** [comment]
So no matter what you do, you never get 100% kernel_task(excluding heavy work). Am I correct?

**Comment by LuletterSoul** [comment]
Not exactly like kernel_task will get 100% at a moment when excuting heavy work, but will be down at around 20-30% CPU usage.

**Comment by erenatas** [comment]
Ok, then I will try to remove DW1830 specific kexts-DSDTs then try it. I wish my DW1830 would arrive.. I have been waiting for almost 2 months now.

**Comment by chenjh-8** [comment]
> Update: This problem may only be appearing on battery.
> 
> While using on Battery:
> 
> 1. Sleep
> 2. Wakeup -> Kernel_task is at 100% and eating 20W.
> 
> While plugged in:
> 
> 1. Sleep
> 2. Wakeup -> Kernel_task is how it needs to be. Eating 3-4W
> 
> An interesting case (Tried it twice)
> 
> 1. Plug it out
> 2. Sleep
> 3. Wakeup -> Kernel_task is at 100% and eating 20W.
> 4. Plug it in
> 5. Sleep
> 6. Wakeup -> Kernel_task is back to how it should have been. Eating 3-4W once again.
> 
> Seriously, what's going on...

@erenatas 
You describe the situation exactly as I do.Expect you to remove DW1830 kexts-DSDTs

**Comment by erenatas** [comment]
@chenjh-8 I will try to do it today.

**Comment by chenjh-8** [comment]
@erenatas have any result?

**Comment by erenatas** [comment]
I have been trying xigtun's efi. I believe it's related to CPUFriendDataProvider. I am trying to check it right now.

**Comment by erenatas** [comment]
@chenjh-8 do you have android file transfer installed?

EDIT: @chenjh-8 do you have VoodooHDA.kext on EFI/Clover/Kexts/Other?

**Comment by chenjh-8** [comment]
@erenatas NO

**Comment by erenatas** [comment]
I really have no idea why but putting it solved my issue. Honestly, it is weird AF. Give it a shot.
@LuletterSoul can you confirm if you have VoodooHDA or not on your kexts?

[VoodooHDA.kext.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3100264/VoodooHDA.kext.zip)

**Comment by kevinshroff** [comment]
For me, I had power management issues with CPU consuming more power than it should (sounds similar to the issues you guys are having) back when I was constructing my EFI. I think it is caused by sound - I found that using layout-id 72 instead of layout-id 30 on my XPS 15 9570 4K i7 8750H fixed those power management issues, but some other people had no problems with layout id 30.

I think by using voodooHDA you would be bypassing the AppleALC sound and thus seeing those power management issues resolve, but I think trying this layout fix and using AppleALC instead is preferable. Try  layout id 72 and let me know if it fixes it

**Comment by erenatas** [comment]
@kevinshroff I had to return to Windows because I needed battery life for my master's degree. I will return back to hackintosh once I get my DW1830 and try it. 

Meanwhile, can you see or control your fans? Because I couldn't manage to and fans kept running in low speed. That might be another reason for having a bad battery life. While doing light tasks it drains up in 2 hours which is very unfortunate.

**Comment by kevinshroff** [comment]
I'm not on macOS currently either and don't plan on being on it for until around another month for when I do a video on it for YouTube. Last time I used it with my EFI my fans were silent and battery life was decent, around 6-7 hrs (I was also undervolted) if I remember correctly. Didn't attempt to control fans so I wouldn't know about that. Your fans running + crap battery life reminds me of when I was using layout id 30.
EDIT: I haven't actually used lulettersoul's EFI yet so I don't know what layout id he currently is using

**Comment by chenjh-8** [comment]
@kevinshroff I had same issues with @erenatas  ,lulettersoul's EFI using layout id  is 30. And he  let me to change  layout id  to 72 earlier https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2#issuecomment-482779467,but it without effect.

**Comment by M69W** [comment]
In the other hand, try to[ Modify macOS CPU Performance](https://github.com/stevezhengshiqi/one-key-cpufriend).
One key to use is easy for everybody in their CPU i5 or i7  even i9

**Comment by LuletterSoul** [comment]
In fact I didn't realize kernel_task 20-30% CPU usage abnormal until I found it's only 5%-6% CPU usage for kernel_task in my desktop machine run High Serria.

What causes the over usage of kernel_task? It confuses me now.

**Comment by M69W** [comment]
https://www.sov2ex.com/?q=Kernel_task

**Comment by RodriMora** [comment]
> I really have no idea why but putting it solved my issue. Honestly, it is weird AF. Give it a shot.
> @LuletterSoul can you confirm if you have VoodooHDA or not on your kexts?
> 
> [VoodooHDA.kext.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3100264/VoodooHDA.kext.zip)

for me this resolve the issue. I used to have 100% kernel usage and now I have 25-30% and the cpu frecuency doesnt stay in 3+ghz all the time and power usage is lower

**Comment by RodriMora** [comment]
> > I really have no idea why but putting it solved my issue. Honestly, it is weird AF. Give it a shot.
> > @LuletterSoul can you confirm if you have VoodooHDA or not on your kexts?
> > [VoodooHDA.kext.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3100264/VoodooHDA.kext.zip)
> 
> for me this resolve the issue. I used to have 100% kernel usage and now I have 25-30% and the cpu frecuency doesnt stay in 3+ghz all the time and power usage is lower

Update: Internal audio works, but Airpods don't work anymore, they connect but dont show as an option on output devices

Update 2: Changing layout in clover>devices>audio to 72 fixed Airpods not working

**Comment by erenatas** [comment]
@RodriMora and you still have VoodooHDA or you deleted and then changed to layout ID?

**Comment by erenatas** [comment]
I have changed my wifi card to DW1830. Installed 10.14.3 by mistake but it seems to be working good right now. I also did not put VoodooHDA kext too. Will give you an update.

**Comment by erenatas** [comment]
This is definitely related to AppleALC.kext.

**Comment by erenatas** [comment]
@LuletterSoul I have solved it with the SSDT that you have provided in https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2 . I believe you should write this in README. 

Now the other problem is, When the system is booted up initially, It uses around ~3 Watts but after waking up from sleep, it is increased to 5-6 Watts, in the same idle state. There might be something else that is causing the decreased battery life. I am closing this issue for now. I will open another ticket related to this when I find some time to do research to find the cause of the problem.

**Comment by chenjh-8** [comment]
@erenatas  Hei man. You solve this issuse by changing wifi card to DW1830  and replacing this SSDT https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2 ?

**Comment by erenatas** [comment]
> @erenatas Hei man. You solve this issuse by changing wifi card to DW1830 and replacing this SSDT #2 ?

Yes. I don't think It was related to DW1830 but replacing the SSDT solved the kernel_task problem for me.

**Comment by LuletterSoul** [comment]
@erenatas Wrong layout id of audio card would cause busy kernel_task.It's mentioned in [bavariancake](https://github.com/bavariancake/XPS9570-macOS)'s repository.

**Comment by erenatas** [comment]
We have the same laptops but you use a different layout id, isn't that weird?

**Comment by andresandiah** [comment]
i also changed the layout id to 72, it fixed the kernel_task issue BUT, it distorts the headphone jack making it unusable
