### ISSUE TITLE
Restart Loop while installing Mojave

### ISSUE THREAD

**Issue by ghost** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#80]
Hello, I have the XPS 15 with the 4K option, every time I get to the installation screen, format the drive as HFS  and then click on install, after the first reboot and then try to boot the new Mojave partition, it doesn't continue and keep rebooting. Can anyone help me ?

**Comment by LuletterSoul** [comment]
Could you provide -v panic log here? If you need help later, please reopen this issue.
