### ISSUE TITLE
触摸板鼠标移动的时候有时候很飘 类似瞬间移动

### ISSUE THREAD

**Issue by qinkangdeid** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#84]
触摸板鼠标移动的时候有时候很飘，经常定位不准 不知道为啥 比如一直在一个地方画圈圈 鼠标一会就自己跳出去了 跟瞬移一样的  使用[bavariancake的EFI](https://github.com/bavariancake/XPS9570-macOS)就没问题  但是他的就不能睡眠 还不知道是啥原因

**Comment by qinkangdeid** [comment]
关联 #21

**Comment by wtdcode** [comment]
最初遇到过这个问题，是VoodooI2C的问题，但是怎么搞定的忘了....

**Comment by qinkangdeid** [comment]
> 最初遇到过这个问题，是VoodooI2C的问题，但是怎么搞定的忘了....

你现在的efi还有这个问题吗？我尝试将其他efi的组合试试看

**Comment by LuletterSoul** [comment]
其他issue认为VirtualSMC & SMCBatteryManager可以解决这个问题。
