### ISSUE TITLE
xps9570-1080p非触摸屏，10.14.6系统耗电很快

### ISSUE THREAD

**Issue by w962402254** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#85]
就开了一个视频软件看三个小时就没有电了，电脑也没有发热等情况，不知道电用到哪里去了，请教大神

**Comment by w962402254** [comment]
![image](https://user-images.githubusercontent.com/27877696/74392416-03654d00-4e42-11ea-8908-fa0b9f52bf59.png)
dian ch电池只有windows下的十分之一，掉电速度非常快

**Comment by LuletterSoul** [comment]
黑苹果系统耗电是正常的
