### ISSUE TITLE
安装二阶段无限重启请教

### ISSUE THREAD

**Issue by mengma021** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#86]
我的机器是xps9570-i7-8750H 4K 版本，下载的Mojave，刷好U盘后，用LuletterSoul大神的EFI文件夹直接替换掉镜像的EFI，U盘安装可以正常完成，没注意到有报错，不过时间很长，大概有两三个小时，最后电脑自动重启进入二阶段硬盘安装，此时苹果图标下面进度条走大概1/4后突然重启，然后进bios，硬盘安装，重启，进bios，无限循环。
想请教各位，有没有碰到类似情况的，这个问题困扰了很久，查了很多资料，没搞定。
感谢。

**Comment by epnode** [comment]
硬盘是SM981？

**Comment by LuletterSoul** [comment]
请提供-v的日志，还有机型的详细信息。我先关闭此问题，如果你尚未解决，可以重新开启。

**Comment by sunny-cmm** [comment]
之前遇到过，好像要把U盘换个USB口才可以继续
