### ISSUE TITLE
XPS 7590

### ISSUE THREAD

**Issue by eksion** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#88]
Will it works on XPS 15 7590 ?

**Comment by chinmayjade** [comment]
No, i dont think so. I think it will need to be updated to support 9th gen intel processors.

**Comment by M69W** [comment]
https://github.com/search?q=XPS+7590

**Comment by LuletterSoul** [comment]
I don't know much about  hackintosh for XPS 15 7590.But If the model own similar graph card UHD630 with 9570, it should work for hardware acceleration.

**Comment by abaza7** [comment]
Works perfectly with my 7590, i7, 4K touch. I have been using these since Mojave now on Catalina 10.15.5
