### ISSUE TITLE
Unable to use bluetooth dongle - bluetooth controller does not switch to usb

### ISSUE THREAD

**Issue by chinmayjade** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#89]
I do not have DW1830 and bought the IOGEAR Bluetooth dongle which has been reported to work with Hackintoshs by a lot of users on Tonymacx86 and other forums.
This dongle uses a Broadcomm chip and is recognized by the system but does not want to activate it. 
I have tried the terminal command below to force the system to use USB Bluetooth dongle by default, which does not seem to work:
`sudo nvram bluetoothHostControllerSwitchBehavior=always`

StackExchange: https://apple.stackexchange.com/questions/94402/force-os-x-to-use-bluetooth-dongle-instead-of-built-in-controller

Using Bluetooth Explorer to switch between Bluetooth controllers:
https://download.developer.apple.com/Developer_Tools/Additional_Tools_for_Xcode_10.2/Additional_Tools_for_Xcode_10.2.dmg

Dongle: https://www.amazon.com/dp/B007GFX0PY/ref=twister_B00898F48I?_encoding=UTF8&th=1
Tonymacx86 posts: https://www.tonymacx86.com/threads/best-bluetooth-adapter-for-hackintosh.185807/

@LuletterSoul Any way you can force disable inbuilt bluetooth controller so that we can use USB dongle?

**Comment by jaromeyer** [comment]
you can disable it in the BIOS under wireless or something

**Comment by chinmayjade** [comment]
Tried to disable but it still wouldnt work. Ended up replacing the Wifi+BT card with BCM94360NG and now both inbuilt and USB bluetooth work!
P.S. I was using an Intel 9260AC card previously.

**Comment by LuletterSoul** [comment]
@chinmayjade 
Thank you for sharing your solution, closing this issue as fixed
