### ISSUE TITLE
触摸板的防触摸

### ISSUE THREAD

**Issue by M69W** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#9]
在9560 上看到：
https://github.com/jardenliu/XPS15-9560-Mojave/commit/54315649dea29f15e40f42c3699faa79fe5f8e75

一些相关的资料：
https://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/
VoodooI2C触摸板驱动教程

**Comment by LuletterSoul** [comment]
请在尝试测试后发起PR。

**Comment by LuletterSoul** [comment]
我会在下一个版本整合。

**Comment by LuletterSoul** [comment]
已整合。
