### ISSUE TITLE
User for dell precision 5530 i7 8850H

### ISSUE THREAD

**Issue by tinhkma** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#91]
Does it work well and accurately on dell precision 5530 i7 8850H laptop?

**Comment by erenatas** [comment]
It is a different device. The best thing you can do is to try it. I bet there will be some problems.

**Comment by LuletterSoul** [comment]
Different models are required different configurations. I don't this this configuration is suitable for you.Closing this issue as unrelated term, please reopen in case you still face common problem.
