### ISSUE TITLE
Installer Stuck Catalina, Mojave, Bios 1.16.2

### ISSUE THREAD

**Issue by hoangcongtuan** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#94]
Hi,
I create setup like your guide: copy efi, using config_install.plist to boot to installer
But it stuck at 2 minutes remaining

Dell XPS 9570
I7 8750H
BIOS 1.16.2

Do you have any solution? i stuck here two days, try two version of catalina and one version of Mojave, it still stuck
Thanks

**Comment by LuletterSoul** [comment]
@hoangcongtuan 
Sorry late for  response, could you provide `-v` logs please?

**Comment by hoangcongtuan** [comment]
> @hoangcongtuan
> Sorry late for response, could you provide `-v` logs please?

the issue was solved!, I replace my pm981 with another, pm961 and I pass it
